copilot-platforms/tasks-app

.github/PULL_REQUEST_TEMPLATE.md

- [OUT-271](https://linear.app/copilotplatforms/issue/OUT-271/update-pr-review-template-to-include-refs-changes-testing-criteria)

OUT-271 | Update pull request template to include testing and review notes

---

src/app/api/core/services/policies.service.ts
src/app/api/core/types/api.ts
src/app/api/core/types/tasks.ts
src/app/api/tasks/tasks.helpers.ts
src/app/api/tasks/tasks.service.ts
src/app/api/users/route.ts
src/app/api/users/users.controller.ts
src/app/api/users/users.service.ts
src/types/common.ts
src/utils/CopilotAPI.ts

- [OUT-285 | Send Notifications and Email on task assigned / completed](https://linear.app/copilotplatforms/issue/OUT-285/send-notifications-and-email-on-task-assigned-completed)
- Depends on https://github.com/copilot-platforms/tasks-app/pull/10

OUT-285 | Send Notifications and Email on task assigned / completed

---

package.json
prisma/migrations/20240514145750_adds_due_date/migration.sql
prisma/schema.prisma
src/app/actions.ts
src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/Sidebar.tsx
src/app/detail/ui/TaskEditor.tsx
src/app/globals.css
src/app/manage-templates/page.tsx
src/app/manage-templates/ui/TemplateBoard.tsx
src/components/inputs/DatePickerComponent.tsx
src/types/dto/tasks.dto.ts
src/types/dto/templates.dto.ts
src/utils/dateHelper.ts
yarn.lock

- [Implement due dates in task](https://linear.app/copilotplatforms/issue/OUT-326/implement-due-dates-in-tasks)
- [LOOM](https://www.loom.com/share/6530082522a94af8b7bff0cb4284cabf?sid=69dd52f6-5a4c-4329-ba32-b91d866e8d69)

OUT-326 Implement Due Dates in Task

---

src/app/ui/TaskBoard.tsx
src/components/cards/TaskColumn.tsx

- [Get rid of column action elements](https://linear.app/copilotplatforms/issue/OUT-390/get-rid-of-column-action-elements)

OUT 390 Get rid of column action elements

---

src/app/client/ui/ClientTaskBoard.tsx
src/app/ui/TaskBoard.tsx
src/components/cards/TaskColumn.tsx
src/components/cards/TaskRow.tsx
src/components/layouts/FilterBar.tsx
src/redux/features/taskBoardSlice.tsx
src/types/interfaces.ts

- [When I filter the tasks, show the count that are visible divided by the total count in each column](https://linear.app/copilotplatforms/issue/OUT-397/when-i-filter-the-tasks-show-the-count-that-are-visible-divided-by-the)
- [LOOM](https://www.loom.com/share/5f499fdd33bf4875b741ba937ad2bdf4)

OUT-397 When I filter the tasks, show the count that are visible divided by the total count in each column

---

src/components/cards/AttachmentCard.tsx
src/components/inputs/Selector.tsx
src/components/layouts/FilterBar.tsx
src/types/interfaces.ts

- [Show client / IU last names for assignee](https://linear.app/copilotplatforms/issue/OUT-395/show-client-iu-last-names-for-assignees)
- [LOOM](https://www.loom.com/share/b1b5dfb02d7843559babb3e07adf99d1)

Out-395 Show client / IU last names for assignees

---

src/components/buttonsGroup/FilterButtonsGroup.tsx
src/components/layouts/FilterBar.tsx

- [When I am filtering on "My tasks", I should not be able to Filter by assignee](https://linear.app/copilotplatforms/issue/OUT-398/when-i-am-filtering-on-my-tasks-i-should-not-be-able-to-filter-by)
- [ LOOM](https://www.loom.com/share/041abd2944434982a53c66117cd226ba)

Out-398 When I am filtering on "My tasks", I should not be able to Filter by assignee

---

src/app/ui/NewTaskForm.tsx

- [If I'm filtering by a user, when I click "New Task", assignee should default to the user I was filtering on](https://linear.app/copilotplatforms/issue/OUT-401/if-im-filtering-by-a-user-when-i-click-new-task-assignee-should)
- [LOOM](https://www.loom.com/share/e65a7de000e8425ba769073dcfbea624)

OUT-401 If I'm filtering by a user, when I click "New Task", assignee should default to the user I was filtering on

---

src/app/api/tasks/tasks.service.ts
src/app/detail/[task_id]/[user_type]/actions.ts
src/app/detail/ui/Sidebar.tsx
src/app/ui/NewTaskForm.tsx
src/components/cards/ListViewTaskCard.tsx
src/components/cards/TaskCard.tsx
src/components/inputs/ExtraOptionRenderer.tsx
src/components/inputs/ExtraOptionRendererAssignee.tsx
src/components/inputs/Selector.tsx
src/components/layouts/FilterBar.tsx
src/hooks/useHandleSelectorComponent.tsx
src/redux/features/createTaskSlice.ts
src/redux/features/templateSlice.tsx
src/types/dto/tasks.dto.ts
src/types/interfaces.ts
src/utils/getAssigneeTypeCorrected.ts
src/utils/noAssignee.ts

- [Allow tasks to have no assignee](https://linear.app/copilotplatforms/issue/OUT-388/allow-tasks-to-have-no-assignee)
- [LOOM](https://www.loom.com/share/7a288d08683a4119bb7f4163ac3a691f)

Out-388 Allow tasks to have no assignee

---

src/app/api/workflow-states/workflowStates.service.ts

- [Get rid of Archived Status](https://linear.app/copilotplatforms/issue/OUT-377/get-rid-of-archived-status)

OUT-377 Get rid of Archived Status

---

src/app/api/tasks/tasks.service.ts
src/app/client/page.tsx
src/app/client/ui/ClientTaskBoard.tsx
src/components/cards/ClientTaskCard.tsx

- [Client-side Mark done should not show up for done tasks](https://linear.app/copilotplatforms/issue/OUT-381/client-side-mark-done-should-not-show-up-for-done-tasks)
- [LOOM](https://www.loom.com/share/04e5d8e663334504b426bd2d6ff2606e)

OUT-381 Client-side Mark done should not show up for done tasks

---

src/app/loading.tsx
src/components/layouts/Loader.tsx

- [Loading spinner for the app](https://linear.app/copilotplatforms/issue/OUT-379/loading-spinner-for-the-app)
- [LOOM](https://www.loom.com/share/1ae2039fe528422e95c5ed535d72b528)

OUT-379 Loading spinner for the app

---

package.json
src/app/detail/[task_id]/[user_type]/page.tsx
src/components/cards/CommentCard.tsx
src/components/inputs/CommentInput.tsx
yarn.lock

- [Comments and Subcomments component](https://linear.app/copilotplatforms/issue/OUT-368/ui-comments-and-subcomments-component)
- [LOOM](https://www.loom.com/share/217b81e2168b467a890c3189ea57dae9)

Out-368 Comments and Subcomments component

---

src/app/ui/NewTaskForm.tsx
src/components/inputs/Selector.tsx

- [UI Bug when I click on the assignee dropdown and then hit escape](https://linear.app/copilotplatforms/issue/OUT-414/ui-bug-when-i-click-on-the-assignee-dropdown-and-then-hit-escape)

OUT-414 UI Bug when I click on the assignee dropdown and then hit escape

---

src/app/api/core/services/policies.service.ts
src/app/api/tasks/[id]/complete/route.ts
src/app/api/tasks/tasks.controller.ts
src/app/api/tasks/tasks.service.ts
src/app/api/users/client/route.ts
src/app/api/users/users.controller.ts
src/app/api/users/users.service.ts
src/app/client/actions.ts
src/app/client/page.tsx
src/app/client/ui/ClientTaskBoard.tsx
src/components/cards/ClientTaskCard.tsx

- [Client-side UI shows "no assignee"](https://linear.app/copilotplatforms/issue/OUT-429/client-side-ui-shows-no-assignee)
- [Client-side Mark done not working](https://linear.app/copilotplatforms/issue/OUT-380/client-side-mark-done-not-working)
- [LOOM](https://www.loom.com/share/daef1e575f424700921d7332c07aef51)
- Handling mark done from client side triggers a notification on task workflowstate changed. On workflowstate changed, the recipent id is taken as createdById of the task. And recipentId is passed to getClient function of copilot sdk because assigneeType will be client. 
Right now tasks are created by IUs, so using getClient() to search creator's id (ius) throws an error. Need some clarity here.

OUT-429 Client-side UI shows "no assignee"

---

prisma/migrations/20240614113212_filter_options_view_settings/migration.sql
prisma/schema.prisma
src/app/actions.ts
src/app/api/view-settings/viewSettings.service.ts
src/app/page.tsx
src/components/buttons/FilterByAssigneeBtn.tsx
src/components/inputs/Selector.tsx
src/components/inputs/ViewModeSelector.tsx
src/components/layouts/FilterBar.tsx
src/hoc/ClientSideStateUpdate.tsx
src/hooks/useHandleSelectorComponent.tsx
src/redux/features/taskBoardSlice.tsx
src/types/dto/viewSettings.dto.ts

- [Save my latest view / filter](https://linear.app/copilotplatforms/issue/OUT-420/save-my-latest-view-filter)
- [LOOM](https://www.loom.com/share/df93c550ab2a4b338043a6cbfd0ed4e9)

OUT-420 Save my latest view / filter

---

prisma/migrations/20240617064530_adds_label_mapping_schema/migration.sql
prisma/migrations/20240617104231_adds_label_column_in_task_schema/migration.sql
prisma/schema.prisma
src/app/actions.ts
src/app/api/activity-logs/[id]/route.ts
src/app/api/attachments/attachments.controller.ts
src/app/api/comment/comment.service.ts
src/app/api/label-mapping/label-mapping.service.ts
src/app/api/notification/notification.helpers.ts
src/app/api/notification/notification.service.ts
src/app/api/tasks/tasks.controller.ts
src/app/api/tasks/tasks.service.ts
src/app/api/upload/route.ts
src/app/api/users/users.controller.ts
src/app/api/view-settings/viewSettings.controller.ts
src/app/api/workflow-states/workflowStates.controller.ts
src/app/client/actions.ts
src/app/client/page.tsx
src/app/detail/[task_id]/[user_type]/actions.ts
src/app/detail/[task_id]/[user_type]/page.tsx
src/app/layout.tsx
src/app/manage-templates/actions.ts
src/app/manage-templates/page.tsx
src/app/page.tsx
src/app/ui/TaskBoard.tsx
src/components/cards/TaskCard.tsx
src/components/inputs/Selector.tsx
src/types/dto/tasks.dto.ts

- [API - Task labelling](https://linear.app/copilotplatforms/issue/OUT-438/api-task-labelling#update-5f96a5f2)

OUT 438 API - Task labelling

---

package.json
src/app/api/view-settings/viewSettings.service.ts
src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/ActivityLog.tsx
src/types/common.ts
src/utils/getTimeDifference.ts
yarn.lock

- [Integration - Integrate activity log and comments list](https://linear.app/copilotplatforms/issue/OUT-333/integration-integrate-activity-log-and-comments-list)
- [LOOM](https://www.loom.com/share/c61f2472686c487fa02eb7140821b2e2)

OUT-333 Integration - Integrate activity log and comments list

---

src/components/inputs/Selector.tsx
src/types/interfaces.ts

- [Assignee group labels are camelCased](https://linear.app/copilotplatforms/issue/OUT-448/assignee-group-labels-are-camelcased)
- [LOOM](https://www.loom.com/share/41b93b020f674515a3a28e44c37c9b2c)

OUT-448 Assignee group labels are camelCased

---

package.json
src/app/detail/ui/styledComponent.tsx
src/app/ui/NewTaskForm.tsx
yarn.lock

- [Integrate Tapwrite in Tasks Create modal](https://linear.app/copilotplatforms/issue/OUT-449/integrate-tapwrite-in-tasks-create-modal)
- [LOOM](https://www.loom.com/share/1d8c7184c10849f8b7fb7f6530462c29)

OUT-449 Integrate Tapwrite in Tasks Create modal

---

src/app/detail/ui/Sidebar.tsx
src/app/ui/NewTaskForm.tsx
src/components/inputs/Selector-WorkflowState.tsx

- [Simplify the status dropdown](https://linear.app/copilotplatforms/issue/OUT-434/simplify-the-status-dropdown)

OUT 434 Simplify the status dropdown

---

src/app/client/ui/ClientTaskBoard.tsx
src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/TaskEditor.tsx
src/app/ui/TaskBoard.tsx

- [Bring back Task Description view w/o Advanced Workflow features](https://linear.app/copilotplatforms/issue/OUT-492/bring-back-task-description-view-wo-advanced-workflow-features)

OUT-492 Bring back Task Description view w/o Advanced Workflow features

---

src/app/detail/ui/Sidebar.tsx

- [Lines not aligned on sidebar](https://linear.app/copilotplatforms/issue/OUT-516/lines-not-aligned-on-sidebar)

OUT-516 Lines not aligned on sidebar

---

src/app/detail/ui/TaskEditor.tsx
src/app/detail/ui/styledComponent.tsx
src/app/ui/NewTaskForm.tsx
yarn.lock

- [Numbered bullets have bad formatting](https://linear.app/copilotplatforms/issue/OUT-517/numbered-bullets-have-bad-formatting)

OUT-517 Numbered bullets have bad formatting

---

src/app/api/core/services/policies.service.ts
src/app/api/users/users.controller.ts
src/app/api/users/users.service.ts
src/app/detail/[task_id]/[user_type]/page.tsx

- [No assignee shown for task assigned to client](https://linear.app/copilotplatforms/issue/OUT-509/no-assignee-shown-for-task-assigned-to-client)

OUT-509 No assignee shown for task assigned to client

---

src/app/client/ui/ClientTaskBoard.tsx
src/app/detail/ui/styledComponent.tsx
src/app/ui/TaskBoard.tsx
src/components/buttons/SecondaryBtn.tsx
src/components/cards/ClientTaskCard.tsx
src/components/cards/ListViewTaskCard.tsx
src/components/cards/TaskCard.tsx

- [OUT-485 | Improve performance for Clicking into a task](https://linear.app/copilotplatforms/issue/OUT-485/improve-performance-for-clicking-into-a-task)
- `prefetch={true}` shouldn't be explicitly mentioned anymore but it will help clarify our decision to use links in the future

OUT-485 | Improve performance for Clicking into a task

---

src/app/ui/NewTaskForm.tsx
src/components/inputs/DatePickerComponent.tsx

- [New task model updates](https://linear.app/copilotplatforms/issue/OUT-486/new-task-model-updates) [OUT-486]

OUT-486 New task model updates

---

src/app/layout.tsx
src/app/ui/TaskBoard.tsx
src/hoc/Interrupt_CmdK.tsx

- [Command K should work in the Tasks App](https://linear.app/copilotplatforms/issue/OUT-535/command-k-should-work-in-the-tasks-app)

OUT-535 Command K should work in the Tasks App

---

package.json
src/hoc/DndWrapper.tsx
yarn.lock

OUT-528, OUT-531 Simplification for editor

---

package.json
yarn.lock

OUT-528 Simplifications for editor

---

src/app/detail/ui/Sidebar.tsx
src/app/globals.css
src/app/ui/TaskBoard.tsx
src/components/cards/TaskColumn.tsx

OUT 526 Two scroll bars on tasks board view

---

src/components/inputs/Selector-WorkflowState.tsx
src/components/inputs/Selector.tsx
src/components/searchBar/index.tsx

- [Better escape-ing logic](https://linear.app/copilotplatforms/issue/OUT-534/better-escape-ing-logic)
- [LOOM](https://www.loom.com/share/2cfbe98f8edb4b6db7cd84a17a20e0c6)

OUT-534 Better escape-ing logic

---

package.json
yarn.lock

OUT-547 Typography updates for task editor

---

src/components/cards/TaskColumn.tsx
src/hoc/CustomScrollbar.tsx

Columns cut off too early on large screens

---

src/components/inputs/DatePickerComponent.tsx

Year Button Background Color - MUI Datepicker

---

src/components/cards/ListViewTaskCard.tsx
src/components/cards/TaskRow.tsx
src/components/inputs/Selector.tsx

- [In list view, improve colors, borders, hover states](https://linear.app/copilotplatforms/issue/OUT-546/in-list-view-improve-colors-borders-hover-states)
- [LOOM](https://www.loom.com/share/a6f2caf317924fdd8c1a75ce2c47e253)

OUT-546 In list view, improve colors, borders, hover states

---

src/app/client/ui/ClientTaskBoard.tsx
src/app/page.tsx
src/app/ui/Modal_NewTaskForm.tsx
src/app/ui/TaskBoard.tsx
src/components/layouts/EmptyState/DashboardEmptyState.tsx

Note: The NewTaskForm modal which is opened using `showModal` state variable was inserted into two different components that were rendered logically. This modal continuously re-renders in both the components which resulted in maximum update depth exceeded error. By using two different instances of modal in both logically rendering components, this issue should resolve.

OUT-559 Fix of React minified error

---

src/app/detail/ui/TaskEditor.tsx

OUT-563 Change placeholder copy on issue details

---

src/app/actions.ts

- [View not being saved](https://linear.app/copilotplatforms/issue/OUT-561/view-not-being-saved)
- [LOOM](https://www.loom.com/share/b67a349ed9aa42e0adf74eebf761cbec)

OUT-561 View not being saved

---

src/app/detail/ui/Sidebar.tsx
src/app/ui/NewTaskForm.tsx
src/components/layouts/FilterBar.tsx

OUT-584 Disable re-assignment in task details

---

prisma/migrations/20240715112440_remove_unique_label_constraint/migration.sql
prisma/schema.prisma
src/app/api/label-mapping/label-mapping.service.ts
src/app/api/tasks/tasks.service.ts
src/lib/prismaExtensions.ts

OUT-581 Task does not have the right code

---

src/components/cards/ClientTaskCard.tsx
src/components/cards/ListViewTaskCard.tsx
src/components/cards/TaskCard.tsx

Hotfix: Turn off prefetching temporarily

---

src/app/detail/ui/TaskEditor.tsx
src/components/inputs/Selector.tsx
src/hooks/useDebounce.ts
yarn.lock

- [Unclear when task update has saved](https://linear.app/copilotplatforms/issue/OUT-578/unclear-when-task-update-has-saved)
- [LOOM](https://www.loom.com/share/cef8c216886c4e8cb73705d9d2510c49)

OUT-578 Unclear when task update has saved

---

src/app/detail/ui/Sidebar.tsx
src/components/inputs/DatePickerComponent.tsx
src/components/layouts/Header.tsx

- [Change text 'Due Date' to 'Due date'](https://linear.app/copilotplatforms/issue/OUT-597/change-text-due-date-to-due-date)
- [Rename button label '+ New task' to maintain consistency](https://linear.app/copilotplatforms/issue/OUT-598/rename-button-label-new-task-to-maintain-consistency)
- [LOOM](https://www.loom.com/share/d81f2da2869c476e8186cd5a2f02c6c0)

OUT-597, OUT-598 Change text 'Due Date' to 'Due date'

---

src/app/ui/NewTaskForm.tsx
src/components/layouts/FilterBar.tsx
src/utils/string.ts
src/utils/users.ts

- [OUT-573 | Search for client has inconsistencies](https://linear.app/copilotplatforms/issue/OUT-573/search-for-client-has-inconsistencies)

OUT-573 | Search for client has inconsistencies

---

src/components/cards/TaskCard.tsx

hotfix: date component alignment in task card

---

src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/ToggleController.tsx

- [Fix Task details page scrolling issue](https://linear.app/copilotplatforms/issue/OUT-608/fix-task-details-page-scrolling-issue)
- [LOOM](https://www.loom.com/share/0383c564e6844788a8bcbd52de2b9792)

OUT-608 Fix Task details page scrolling issue

---

package.json
yarn.lock

OUT-589 Editor/Formatter doesn't work as expected on Task creation modal

---

package.json
src/app/tapwrite.css
yarn.lock

OUT-618 Rich text editor formatting incorrect on task details

---

package.json
src/app/api/notification/notification.helpers.ts
src/app/api/notification/notification.service.ts
src/app/page.tsx
src/hoc/ClientSideStateUpdate.tsx
src/utils/redirect.ts
yarn.lock

- [OUT-538 | Task details navigation](https://linear.app/copilotplatforms/issue/OUT-538/task-details-navigation)
- [Tasks Notifications RD](https://copilotplatforms.notion.site/Notification-Scenarios-4f815a6dbe7e423f87f33f33cfbc55ff)

OUT-538 | Task details navigation

---

src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/Sidebar.tsx
src/components/inputs/DatePickerComponent.tsx

OUT 665 There is an “Invalid date” Message when changing the due date for a task

---

src/app/detail/[task_id]/[user_type]/page.tsx
src/components/buttons/SecondaryBtn.tsx

- [OUT-646 | Remove selected state of Tasks breadcrumbs](https://linear.app/copilotplatforms/issue/OUT-646/remove-selected-state-of-tasks-breadcrumbs)

OUT-646 | Remove selected state of Tasks breadcrumbs

---

src/components/cards/ClientTaskCard.tsx

- [Task doesn´t look good on mobile when task without due date](https://linear.app/copilotplatforms/issue/OUT-640/task-doesn%C2%B4t-look-good-on-mobile-when-task-without-due-date)
- [LOOM](https://www.loom.com/share/5b17b8ed430f4a039b98ae0f77630402)

OUT-640 Task doesn´t look good on mobile when task without due date

---

src/app/api/tasks/tasks.service.ts
src/app/client/page.tsx
src/app/client/ui/ClientTaskBoard.tsx
src/app/page.tsx
src/app/ui/Modal_NewTaskForm.tsx
src/app/ui/TaskBoard.tsx
src/redux/features/taskBoardSlice.tsx
src/types/dto/tasks.dto.ts
src/utils/sortTask.ts

OUT 661 Default order of tasks should be most recent at the top

---

src/app/api/tasks/tasks.service.ts
src/app/api/users/users.controller.ts
src/app/api/users/users.service.ts
src/app/client/actions.ts
src/app/client/ui/ClientTaskBoard.tsx
src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/Sidebar.tsx
src/app/page.tsx
src/components/inputs/DatePickerComponent.tsx
src/hoc/ClientSideStateUpdate.tsx

OUT-667, OUT-647, OUT-668 Issues with realtime updates

---

src/components/cards/ListViewTaskCard.tsx
src/components/inputs/Selector.tsx
src/components/layouts/FilterBar.tsx

- filter by assignee removed when my tasks is clicked in filter button options
- [Filter by assignee' is shown in mobile view even if IU selects 'My tasks' filter](https://linear.app/copilotplatforms/issue/OUT-653/filter-by-assignee-is-shown-in-mobile-view-even-if-iu-selects-my-tasks)
- [Filter by assignee' drop-down shows the 'No assignee' option in mobile experience. but it is not shown on the desktop view.](https://linear.app/copilotplatforms/issue/OUT-650/filter-by-assignee-drop-down-shows-no-assignee-option-on-mobile-but)
- [LOOM](https://www.loom.com/share/d2414f943c804c568e9f7c7b1fe1a19a)

OUT-653, OUT-650 Filter by assignee' is shown in mobile view even if IU selects 'My tasks' filter

---

src/components/cards/TaskCard.tsx
src/components/cards/TaskColumn.tsx

- [Improve click target for task item](https://linear.app/copilotplatforms/issue/OUT-674/improve-click-target-for-task-item)
- [LOOM](https://www.loom.com/share/10816b44ee3d430fbf93201b885d86bc)

OUT-674 Improve click target for task item

---

src/app/ui/NewTaskForm.tsx

- [Assignee drop-down on the task creation pop-up shows options according to selected filters](https://linear.app/copilotplatforms/issue/OUT-673/assignee-drop-down-on-the-task-creation-pop-up-shows-options-according)
- [LOOM](https://www.loom.com/share/2d279978438d4a009423c3385b56aec3)

OUT-673 Assignee drop-down on the task creation pop-up shows options according to selected filters

---

src/app/ui/TaskBoard.tsx
src/components/cards/ListViewTaskCard.tsx
src/components/cards/TaskCard.tsx
src/components/cards/TaskColumn.tsx
src/hoc/CustomLink.tsx

OUT-675 Extra scrollbars on Tasks

---

src/app/detail/ui/Sidebar.tsx

OUT-680 Sometimes Assignee shows 'unassigned' on task details page

---

src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/TaskEditor.tsx
src/hoc/RealTime.tsx
src/utils/redirect.ts

- [OUT-662 | Deleting task shows error on client side](https://linear.app/copilotplatforms/issue/OUT-662/deleting-task-shows-error-on-client-side)

OUT-662 | Deleting task shows error on client side

---

src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/Sidebar.tsx
src/hoc/ClientSideStateUpdate.tsx

Note: 
This PR added console.log for debugging. Now, this PR wants to gets merged with main to remove those logs.

debug:OUT-680

---

src/app/detail/ui/TaskEditor.tsx

OUT-637 Task title shows in Grey color on task details page on Client side.

---

src/app/api/users/users.service.ts

- [OUT-648 | Filter drop-down shows companies even if companies are disabled](https://linear.app/copilotplatforms/issue/OUT-648/filter-drop-down-shows-companies-even-if-companies-are-disabled)
- While testing this, please make sure to remember to turn *off* Enable companies from dashboard settings. Also remember to toggle it back on after testing.

OUT-648 | Filter drop-down shows companies even if companies are disabled

---

src/components/buttons/TertiaryBtn.tsx
src/components/buttonsGroup/FilterButtonsGroup.tsx
src/components/cards/ClientTaskCard.tsx
src/components/layouts/FilterBar.tsx
src/components/searchBar/index.tsx

- [Filtering area doesn't look good on mobile.](https://linear.app/copilotplatforms/issue/OUT-649/filtering-area-doesnt-look-good-on-mobile)
- [LOOM](https://www.loom.com/share/0e6fb81c0e144aaab837ba6a492a1b15)

OUT-649 Filtering area doesn't look good on mobile.

---

package.json
src/app/api/core/services/base.service.ts
src/app/api/core/utils/authenticate.ts
src/app/api/label-mapping/label-mapping.service.ts
src/cmd/load-testing/deleteClients.ts
src/cmd/load-testing/index.ts
src/cmd/load-testing/load-testing.config.json
src/cmd/load-testing/load-testing.service.ts
src/types/basic.ts
src/types/common.ts
src/utils/CopilotAPI.ts
src/utils/random.ts
tsconfig.json
yarn.lock

- [OUT-548 | Load Testing](https://linear.app/copilotplatforms/issue/OUT-548/load-testing)
- Make sure to add a `LOAD_TESTING_COPILOT_TOKEN` env variable to your `.env` file with an IU token corresponding with your chosen workspace

OUT-548 | Load Testing

---

src/app/api/core/exceptions/api.ts
src/app/api/core/utils/withErrorHandler.ts
src/app/api/webhook/route.ts
src/app/api/webhook/webhook.controller.ts
src/app/api/webhook/webhook.service.ts
src/types/webhook.ts

- [OUT-687 | Add endpoint for receiving webhooks](https://linear.app/copilotplatforms/issue/OUT-687/add-endpoint-for-receiving-webhooks)

OUT-687 | Add endpoint for receiving webhooks

---

src/app/api/core/exceptions/api.ts
src/app/api/core/utils/withErrorHandler.ts
src/app/api/webhook/route.ts
src/app/api/webhook/webhook.controller.ts
src/app/api/webhook/webhook.service.ts
src/types/webhook.ts

- [OUT-688 | Delete task when assignee is deleted](https://linear.app/copilotplatforms/issue/OUT-688/delete-task-when-assignee-is-deleted)

OUT-688 | Delete task when assignee is deleted

---

src/components/layouts/ConfirmDeleteUI.tsx

- [use correct confirmation dialog](https://linear.app/copilotplatforms/issue/OUT-706/use-correct-confirmation-dialog)

OUT-706 use correct confirmation dialog

---

src/components/cards/ClientTaskCard.tsx
src/utils/getMaxAssigneeNameWidth.ts

- [Assignee shows with ellipse on client end on mobile](https://linear.app/copilotplatforms/issue/OUT-683/assignee-shows-with-ellipse-on-client-end-on-mobile)
- [LOOM](https://www.loom.com/share/9b19c7e5e4a34ede81ca0a0c6bc06a0e)

OUT-683 Assignee shows with ellipse on client end on mobile

---

src/components/cards/ClientTaskCard.tsx
src/components/cards/ListViewTaskCard.tsx

- [Tasks shown in List view are not aligned properly due to task ID](https://linear.app/copilotplatforms/issue/OUT-714/tasks-shown-in-list-view-are-not-aligned-properly-due-to-task-id)
- [Fix 'Due date' visibility on CU end](https://linear.app/copilotplatforms/issue/OUT-723/fix-due-date-visibility-on-cu-end)
- [LOOM](https://www.loom.com/share/ff9a33e16feb4457bf98ad1d3db3b8d0)

OUT-714,OUT-723 Tasks shown in List view are not aligned properly due to task ID

---

src/utils/extractHtml.ts

- [Special character '&' is shown as '&' on task list page on client end](https://linear.app/copilotplatforms/issue/OUT-722/special-character-and-is-shown-as-andamp-on-task-list-page-on-client)

OUT-722 Special character '&' is shown as '&' on task list page on client end

---

src/app/detail/ui/Sidebar.tsx
src/components/atoms/CopilotAvatar.tsx

- [Default User avatar is not shown correctly for Tasks app](https://linear.app/copilotplatforms/issue/OUT-717/default-user-avatar-is-not-shown-correctly-for-tasks-app)
- [Fix Properties div size in Mobile view](https://linear.app/copilotplatforms/issue/OUT-713/fix-properties-div-size-in-mobile-view)
- [LOOM](https://www.loom.com/share/8c8f5e64987947328539fe54049acb58)

OUT-717, OUT-713 Default User avatar is not shown correctly for Tasks app

---

src/app/api/tasks/tasks.service.ts
src/components/layouts/Loader.tsx

- [OUT-719 | Changing task status to ToDo/In-Progress, updates the notifications and triggers task completion notifications to IU.](https://linear.app/copilotplatforms/issue/OUT-719/changing-task-status-to-todoin-progress-updates-the-notifications-and)

OUT-719 | Changing task status to ToDo/In-Progress, updates the notifications and triggers task completion notifications to IU.

---

src/app/detail/ui/TaskEditor.tsx

- [Open Tasks button from notifications opens Connection closed error](https://linear.app/copilotplatforms/issue/OUT-691/open-tasks-button-from-notifications-opens-connection-closed-error)
- [LOOM](https://www.loom.com/share/79174af4aa764388a74585f12b0944ac)

OUT-691 Open Tasks button from notifications opens Connection closed error

---

src/app/error.tsx
src/config/index.ts

- [Hide sensitive error messages from production](https://linear.app/copilotplatforms/issue/OUT-734/hide-sensitive-error-messages-from-production)
- [LOOM](https://www.loom.com/share/c3e0e3f23e1f43c0a5cdc3a9a93078b1)
- In the loom video, I first created a fetch failed error by inserting random string in VERCEL_ENV variable, and for the second time I changed the VERCEL_ENV variable to 'production' which still causes fetch failed error locally, but the error is masked here.

OUT-734 Hide sensitive error messages from production

---

src/components/searchBar/index.tsx

- [Improve 'Search' option UI](https://linear.app/copilotplatforms/issue/OUT-710/improve-search-option-ui)
- [LOOM](https://www.loom.com/share/942055c55d9047ed94083c07ecbd1515)

OUT-710 Improve 'Search' option UI

---

src/components/layouts/FilterBar.tsx
src/utils/assignee.ts

- [Cross icon is not shown when filter by company](https://linear.app/copilotplatforms/issue/OUT-740/cross-icon-is-not-shown-when-filter-by-company)
- [LOOM](https://www.loom.com/share/1e30aa307b304bb28f17964c743b902d)

OUT-740 Cross icon is not shown when filter by company

---

src/app/api/tasks/tasks.controller.ts
src/app/api/tasks/tasks.service.ts

- [OUT-654-re | Improving task details opening experience](https://linear.app/copilotplatforms/issue/OUT-654/improving-task-details-opening-experience-video-shows-laggy-navigation)

OUT-654 | Backend Optimizations for Improving task details opening experience

---

src/app/client/page.tsx

- [Error: Unable to authorize Copilot SDK.](https://linear.app/copilotplatforms/issue/OUT-642/error-unable-to-authorize-copilot-sdk)

OUT-642 | Prevent invalid / missing token to propagate over app flow

---

src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/TaskEditor.tsx
src/hoc/CustomScrollbar.tsx

- [Unnecessary scrollbar is shown on task details page when opening task from notifications.](https://linear.app/copilotplatforms/issue/OUT-678/unnecessary-scrollbar-is-shown-on-task-details-page-when-opening-task)
- [LOOM](https://www.loom.com/share/b47d33478ed0485eb109f22e3ead8798)

OUT-678 Unnecessary scrollbar is shown on task details page when opening task from notifications.

---

package.json
src/app/client/page.tsx
src/app/client/ui/ClientTaskBoard.tsx
src/app/page.tsx
src/app/ui/TaskBoard.tsx
src/hoc/RealTime.tsx
src/redux/features/taskBoardSlice.tsx
src/utils/sortTask.ts

OUT-733 Default order of tasks should be most recent at the top

---

src/app/ui/NewTaskForm.tsx
src/components/inputs/DatePickerComponent.tsx
src/components/inputs/Selector-WorkflowState.tsx
src/components/inputs/Selector.tsx
src/components/searchBar/index.tsx
src/theme/theme.ts
src/types/theme.d.ts

- [Remove alt text/tootlip from some elements](https://linear.app/copilotplatforms/issue/OUT-744/remove-alt-texttootlip-from-some-elements)
- [LOOM](https://www.loom.com/share/57514af4e48c4ecba1d149ffbf8951dc)

OUT-744 Remove alt text/tootlip from some elements

---

src/components/inputs/ListComponent.tsx
src/components/inputs/Selector.tsx

- [consistent scrollbar styling](https://linear.app/copilotplatforms/team/OUT/active)
- [LOOM](https://www.loom.com/share/34c475fd17c34feb8e86f31e4423465e)

OUT-705 consistent scrollbar styling

---

README.md
src/app/api/tasks/tasks.service.ts

Hotfix: Trigger notifications if IU changes client / company task from complete to incomplete

---

src/app/_fetchers/AssigneeFetcher.tsx
src/app/page.tsx
src/app/ui/Modal_NewTaskForm.tsx
src/app/ui/NewTaskForm.tsx
src/components/layouts/FilterBar.tsx
src/redux/features/createTaskSlice.ts

- [On task creation modal, Assignee drop-down shows a "Required" error even after assignee is selected](https://linear.app/copilotplatforms/issue/OUT-755/on-task-creation-modal-assignee-drop-down-shows-a-required-error-even)
- [Simultaneous task creation in very less interval of time causes an error.](https://linear.app/copilotplatforms/issue/OUT-763/simultaneous-task-creation-in-very-less-interval-of-time-causes-an)
- [LOOM](https://www.loom.com/share/245463dfa3ab463c928f2d121d1f19a7)

OUT-755, OUT-763 On task creation modal, Assignee drop-down shows a "Required" error even after assignee is selected

---

src/app/api/notification/notification.service.ts
src/app/api/tasks/tasks.service.ts
src/app/api/webhook/webhook.controller.ts
src/app/api/webhook/webhook.service.ts

- [OUT-748 | Tasks & notifications don't appear & disappear in real-time on company assignment/unassignment](https://linear.app/copilotplatforms/issue/OUT-748/tasks-and-notifications-dont-appear-and-disappear-in-real-time-on)
- Hotfix: edge case while editing task where notification was triggered

OUT-748 | Tasks & notifications don't appear & disappear in real-time on company assignment/unassignment + Fix Notification flow for task update

---

src/components/layouts/FilterBar.tsx
src/utils/users.ts

- ["Filter by assignee" drop-down doesn't work as expected](https://linear.app/copilotplatforms/issue/OUT-750/filter-by-assignee-drop-down-doesnt-work-as-expected

OUT-750-hotfix

---

src/components/layouts/FilterBar.tsx

- [Search does not work properly on mobile](https://linear.app/copilotplatforms/issue/OUT-768/search-does-not-work-properly-on-mobile)
- [LOOM](https://www.loom.com/share/9d91f263bf894e6bbb98a58b89d53c5e)

OUT-768 Search does not work properly on mobile

---

package.json
yarn.lock

- [TypeError: Cannot read properties of undefined (reading '0')](https://linear.app/copilotplatforms/issue/OUT-720/typeerror-cannot-read-properties-of-undefined-reading-0)
- [https://linear.app/copilotplatforms/issue/OUT-698/typeerror-cannot-read-properties-of-undefined-reading-ref](https://linear.app/copilotplatforms/issue/OUT-698/typeerror-cannot-read-properties-of-undefined-reading-ref)
- TBD (this is an issue reported by sentry)
- PR : https://github.com/aatbip/tapwrite/pull/9 (published this version at [npm](https://www.npmjs.com/package/tapwrite)

OUT-720, OUT-698 TypeError: Cannot read properties of undefined (reading '0')

---

prisma/migrations/20240821124316_add_internal_user_notifications_table/migration.sql
prisma/schema.prisma
src/app/api/notification/notification.service.ts
src/app/api/tasks/tasks.service.ts
src/utils/CopilotAPI.ts

- [OUT-746 | Remove task notifications associated with deleted task & deleted company for IU](https://linear.app/copilotplatforms/issue/OUT-746/remove-task-notifications-associated-with-deleted-task-and-deleted)

OUT-746 | Remove task notifications associated with deleted task & deleted company for IU

---

src/app/client/page.tsx
src/app/detail/[task_id]/[user_type]/page.tsx
src/app/page.tsx
src/utils/CopilotAPI.ts

- [OUT-790 | Improve logging for all parts of Tasks App](https://linear.app/copilotplatforms/issue/OUT-790/improve-logging-for-all-parts-of-tasks-app)
- [OUT-774 | Unable to authorize Copilot SDK](https://linear.app/copilotplatforms/issue/OUT-774)

OUT-790 | OUT-774 | Improve logging for all parts of Tasks App | Unable to authorize Copilot SDK

---

src/app/api/notification/notification.service.ts
src/app/api/tasks/tasks.service.ts
src/app/api/webhook/webhook.service.ts

- [OUT-803 | IU with access permissions does not receive task completion notifications.](https://linear.app/copilotplatforms/issue/OUT-803/iu-with-access-permissions-does-not-receive-task-completion)

OUT-803 | IU with access permissions does not receive task completion notifications.

---

src/app/detail/ui/Sidebar.tsx

- Go to the details page
- Notice the loading state layout of Sidebar, and then the loaded state layout of the Sidebar to realize the margins are corrected between the layout change
- Notice that the alignment of the layouts between loading and loaded states are same

OUT-815 Client details -- loading of status/assignee/due date

---

src/app/api/notification/notification.service.ts

- [OUT-807 | Remove task assignment notifications from the notification center for deleted task assigned to IUs](https://linear.app/copilotplatforms/issue/OUT-807/remove-task-assignment-notifications-from-the-notification-center-for)
- Merge to main

OUT-807 | Remove task assignment notifications from the notification center for deleted task assigned to IUs

---

package.json
yarn.lock

- [Change cursor & insert new line when cursor moved below image](https://linear.app/copilotplatforms/issue/OUT-826/change-cursor-and-insert-new-line-when-cursor-moved-below-image)
- [Selecting an image should show a border around the image](https://linear.app/copilotplatforms/issue/OUT-828/selecting-an-image-should-show-a-border-around-the-image)
- [Sometimes, the image flickers while resizing in task details page](https://linear.app/copilotplatforms/issue/OUT-824/sometimes-the-image-flickers-while-resizing-in-task-details-page)
- [LOOM](https://www.loom.com/share/10af791c5c544b4fb9a233ae291813ff)
- There are some complications here which will be solved asap, like cursor not going automatically below the image if there are no nodes below the image while image is being uploaded. This will …

OUT-826, OUT-828, OUT-824  Change cursor & insert new line when cursor moved below image

---

package.json
yarn.lock

- [Cannot type below the image placeholder while the image being uploaded](https://linear.app/copilotplatforms/issue/OUT-829/cannot-type-below-the-image-placeholder-while-the-image-being-uploaded)
- Testing it on preview if there is rangeError. update : feature not working properly, there is a range error. working on this

OUT-829 Cannot type below the image placeholder while the image being uploaded

---

package.json
src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/styledComponent.tsx
yarn.lock

- [Update max width for Task Detail to be 600px.](https://linear.app/copilotplatforms/issue/OUT-805/update-max-width-for-task-detail-to-be-600px)
- [tapwritecommit](https://github.com/aatbip/tapwrite/pull/9/commits/4b279576b84ddeba63a7cbdf225de613e30877b8)
- [LOOM](https://www.loom.com/share/ac5602ad9dd240128411a0a4c06d8e76)

OUT-805 Update max width for Task Detail to be 600px.

---

src/components/layouts/FilterBar.tsx

OUT 834 Tabs and the filter assignee drop-down are shown for Client in mobile view

---

package.json
yarn.lock

- [image resizing issues in real time.](https://linear.app/copilotplatforms/issue/OUT-856/image-resizing-issues-in-real-time)
- [LOOM](https://www.loom.com/share/ea200ed77a0f4b3dbd614bd3d9b9296a)

OUT-856 image resizing issues in real time.

---

src/app/globals.css
src/components/cards/TaskColumn.tsx
src/types/theme.d.ts

[LOOM](https://www.loom.com/share/73ed283447324abca6af1ee287516f28?sid=bb40d368-8620-4958-bb7d-9b475771c9a7)

OUT-809 Scrolling issue for mobile view

---

src/app/globals.css
src/app/ui/TaskBoard.tsx

[LOOM](https://www.loom.com/share/73ed283447324abca6af1ee287516f28?sid=bb40d368-8620-4958-bb7d-9b475771c9a7)

OUT-809 Scrolling issue for mobile view 

---

package.json
yarn.lock

Please find the Tapwrite commit [here](https://github.com/aatbip/tapwrite/commit/bc62c7b55f4783ac905f0e50e8452bd1c8cb02f8)

OUT-865, OUT-874, OUT-873 Issues with redo/undo (history extension in Tapwrite)

---

package.json
src/app/ui/NewTaskForm.tsx
src/components/layouts/FilterBar.tsx
src/hooks/useHandleSelectorComponent.tsx
src/types/interfaces.ts
yarn.lock

- ['Required' error is not shown for the 'Assignee' drop-down and able to create task](https://linear.app/copilotplatforms/issue/OUT-833/required-error-is-not-shown-for-the-assignee-drop-down-and-able-to)
- [MaxWidth is not right on images on smaller screen when screen is changed from devtools. Image max width greater in task creation.](https://linear.app/copilotplatforms/issue/OUT-861/maxwidth-is-not-right-on-images-on-smaller-screen-when-screen-is)

OUT-833 'Required' error is not shown for the 'Assignee' drop-down and able to create task

---

src/hoc/DndWrapper.tsx
src/hoc/ModifiedBackend.ts

- [DND not working on task creation](https://linear.app/copilotplatforms/issue/OUT-883/dnd-not-working-on-task-creation)

OUT-883 DND not working on task creation

---

src/app/ui/TaskBoard.tsx
src/components/buttons/AddBtn.tsx
src/components/cards/TaskCard.tsx
src/components/cards/TaskColumn.tsx
src/hoc/DragDropHandler.tsx

- [Equalize left and right padding for status columns](https://linear.app/copilotplatforms/issue/OUT-868/equalize-left-and-right-padding-for-status-columns)
- [Plus button in statuses is missing Hover and Focus state](https://linear.app/copilotplatforms/issue/OUT-867/plus-button-in-statuses-is-missing-hover-and-focus-state)
- [Adjust + button alignment](https://linear.app/copilotplatforms/issue/OUT-869/adjust-button-alignment)
- [LOOM](https://www.loom.com/share/3ed541c737d24d2d8616c50a7362aac1)

OUT-868, OUT-867, OUT-869 Equalize left and right padding for status columns

---

.env.example

- Updates `.env.example` to include recent env fields for cron, supabase storage, etc

qol/001 - Update env example

---

src/utils/getTimeDifference.ts

OUT 913 Fix pluralization issues with elapsed time in activity feed and comments

---

src/components/cards/CommentCard.tsx
src/utils/getTimeDifference.ts

**DANGER**
Don't merge before #349. This PR depends on it.

OUT 909 Add separator circle to comment blocks and adjust its color

---

src/components/cards/CommentCard.tsx
src/components/inputs/CommentInput.tsx
src/utils/getTimeDifference.ts

**DANGER**
Don't merge before #348. This PR depends on it.
- [LOOM](https://www.loom.com/share/6bf66b68665e47d1aa3e334608e03a2d)

OUT 907 Pressing the enter key should submit a comment form

---

src/app/detail/ui/ActivityLog.tsx
src/app/detail/ui/Comments.tsx
src/components/cards/CommentCard.tsx

[Screencast from 22-10-24 12:06:27 PM +0545.webm](https://github.com/user-attachments/assets/efda1652-071c-48c2-a717-d328a85954d9)

OUT 916 Adjust the default profile icon in activity feed & comments for when a user does not have an image set

---

src/app/detail/ui/ActivityLog.tsx
src/app/detail/ui/Comments.tsx
src/components/inputs/CommentInput.tsx

[Screencast from 22-10-24 07:50:37 PM +0545.webm](https://github.com/user-attachments/assets/7b4f276d-d543-4acd-9935-aceaa847bbc1)

OUT-924 Fix styles on the profile picture avatar

---

src/app/detail/ui/Sidebar.tsx

- CU should only see hover state on Status 
- IU should only see hover state on Status and Due Date

OUT 928 Change hover states based on IU/CU

---

src/app/client/page.tsx
src/app/detail/[task_id]/[user_type]/page.tsx
src/app/page.tsx
src/hoc/RealTime.tsx

- [OUT-957 Issues with "something went wrong" open tasks](https://linear.app/copilotplatforms/issue/OUT-957/issues-with-something-went-wrong-open-tasks)
This changes how tokenPayload is accessed in the Realtime component. Previously this component use redux state to access this value. The value in the redux state gets set using a separate useEffect. There were logs that showed this userId from tokenPayload was undefined even though that should be passed in correctly.

fix(OUT-957): use tokenPayload directly in realtime component

---

src/app/api/comment/comment.service.ts
src/app/api/core/types/tasks.ts
src/app/api/notification/notification.helpers.ts
src/app/api/notification/notification.service.ts

- [Task](Task Link)
- Dependencies on other PRs, any required changes in config/setup to test behaviour, or links to external documents, threads, etc -- if any of them are required

fix: consolidate determining recipients for comment notifs

---

src/app/detail/ui/ActivityWrapper.tsx

- [Task](Task Link)
https://www.loom.com/share/84feade89a054c8ba79b13d934f7283b?sid=6be30542-f942-4eb8-829e-05e73284c523
- Dependencies on other PRs, any required changes in config/setup to test behaviour, or links to external documents, threads, etc -- if any of them are required

chore: remove trailing slash causing 308

---

package.json
src/components/inputs/CommentInput.tsx
yarn.lock

[Screencast from 2024-10-24 20-27-25.webm](https://github.com/user-attachments/assets/2bb5318f-1bce-4a2f-a377-5dc50a83f9de)

OUT-952 | Enter on comment creates extra new line

---

src/components/buttons/ListBtn.tsx

- [Delete button in comments opacity issue](https://linear.app/copilotplatforms/issue/OUT-969/delete-button-in-comments-opacity-issue)

OUT-969 Delete button in comments opacity issue

---

src/app/detail/ui/ActivityWrapper.tsx
yarn.lock

- [Align profile circles with activity title](https://linear.app/copilotplatforms/issue/OUT-936/align-profile-circles-with-activity-title)

OUT-936 Align profile circles with activity title

---

src/components/AttachmentLayout.tsx

- [Internal QA reports](https://linear.app/copilotplatforms/issue/OUT-989/internal-qa-reports)

OUT-989 Internal QA reports

---

src/utils/generateRandomString.ts

- [PNGs not uploading](https://linear.app/copilotplatforms/issue/OUT-994/pngs-not-uploading)

OUT-994 PNGs not uploading

---

package.json
src/components/inputs/CommentInput.tsx
yarn.lock

OUT-1009 Adjust vertical spacing of text input in comment box

---

package.json
yarn.lock

- [Remove upload button from client user's task description page](https://linear.app/copilotplatforms/issue/OUT-1013/remove-upload-button-from-client-users-task-description-page)

OUT-1013 Remove upload button from client user's task description page

---

src/app/ui/Modal_NewTaskForm.tsx
src/app/ui/NewTaskForm.tsx
src/utils/escapeHandler.ts

[Screencast from 12-11-24 12:47:18 PM +0545.webm](https://github.com/user-attachments/assets/17ab9836-c74c-4283-9fde-8eb03f116684)

OUT 991 When I have the formatting menu open and hit 'Escape' I want to close the formatting menu instead of being taken back to the all tasks views

---

src/app/api/tasks/tasks.controller.ts
src/app/api/tasks/tasks.helpers.ts
src/app/api/tasks/tasks.service.ts
src/utils/request.ts

[Screencast from 2024-11-18 15-45-42.webm](https://github.com/user-attachments/assets/e9bc1c65-5ed7-418d-a7a2-4ce7032ab75f)

OUT-1020 | Add Support for Tasks showArchived & showUnarchived Filters in Tasks List API

---

package.json
src/app/api/core/types/user.ts
src/app/client/page.tsx
src/app/detail/ui/ActivityWrapper.tsx
src/app/detail/ui/Comments.tsx
src/app/page.tsx
src/hooks/useScrollToElement.ts
src/utils/redirect.ts
yarn.lock

- ['View Comment' email action should redirect to task comment section](https://linear.app/copilotplatforms/issue/OUT-933/view-comment-email-action-should-redirect-to-task-comment-section)
- [LOOM](https://www.loom.com/share/504bc10765f14c57b423128f39dbaf6d)

OUT-933 | 'View Comment' email action should redirect to task comment section

---

src/components/inputs/ViewModeSelector.tsx
src/components/layouts/FilterBar.tsx

- [LOOM](https://www.loom.com/share/5d9f221b5fc548688bade26481ee6e4d)

OUT-1045 | Bring back old view mode selector for cu view

---

src/app/_fetchers/TaskDataFetcher.tsx
src/app/ui/TaskBoard.tsx
src/components/layouts/EmptyState/NoFilteredTasksState.tsx
src/redux/features/taskBoardSlice.tsx

[Screencast from 2024-11-20 17-49-57.webm](https://github.com/user-attachments/assets/7e8d2c80-379c-4e86-b09e-beac1bbe21f5)

OUT-1042 | Implement 'No tasks found' state

---

src/app/_fetchers/TaskDataFetcher.tsx
src/app/ui/TaskBoard.tsx
src/components/inputs/DisplaySelector.tsx
src/hoc/RealTime.tsx
src/redux/features/taskBoardSlice.tsx

- [LOOM](https://www.loom.com/share/c28b4ada689f48309b3a17ee91a498a9)

OUT-1052 In list & kanban view, Task cards with a new status glitch back and forth when toggles are changed, they always end up in the correct status

---

src/components/inputs/DatePickerComponent.tsx

OUT-1057 | Remove leading zero from dates with single digits

---

src/app/detail/[task_id]/[user_type]/page.tsx

OUT-1068 | Hide archive/unarchive button on tasks details page for CUs

---

src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/ArchiveWrapper.tsx

[Screencast from 27-11-24 11:00:44 AM +0545.webm](https://github.com/user-attachments/assets/777b2e40-4849-4b9c-9626-7f14a49b7e44)

OUT 1088 Show archived timestamp at the top of the task for clients

---

src/app/_fetchers/TaskDataFetcher.tsx
src/app/ui/TaskBoard.tsx

[Screencast from 27-11-24 10:39:45 AM +0545.webm](https://github.com/user-attachments/assets/219fb461-862b-4d00-8a2f-ca339fe426ef)

OUT 1086 Empty states are not shown for IU and CU

---

src/app/detail/ui/Sidebar.tsx

- [LOOM](https://www.loom.com/share/b51792409ca949c69092f7f2a710f6d2)

OUT-1090 | Task details page header and properties header are misaligned

---

prisma/migrations/20241202091321_add_new_templates_schema/migration.sql
prisma/schema/taskTemplate.prisma
prisma/schema/workflowState.prisma
src/app/api/tasks/templates/[id]/route.ts
src/app/api/tasks/templates/templates.controller.ts
src/app/api/tasks/templates/templates.service.ts
src/app/manage-templates/ui/TemplateBoard.tsx
src/types/dto/templates.dto.ts

[Screencast from 2024-12-02 15-01-34.webm](https://github.com/user-attachments/assets/df00ec35-0b1d-46e5-a48e-d7d4c1249f9c)

OUT-1059 | Implement Templates API with new Template Schema

---

src/app/manage-templates/ui/TemplateBoard.tsx
src/app/manage-templates/ui/TemplateForm.tsx
src/app/tapwrite.css
src/redux/features/templateSlice.tsx
src/types/interfaces.ts

OUT-1081 | Add Dummy modal for new Create Template design

---

src/app/api/tasks/templates/templates.service.ts
src/app/manage-templates/page.tsx
src/app/manage-templates/ui/TemplateForm.tsx
src/types/dto/templates.dto.ts
src/utils/inlineImage.ts

- [LOOM](https://www.loom.com/share/a5daed30faf441a491768860c57e34c6)

OUT-1082 | API Integration for Create Template Modal

---

src/app/ui/MenuBoxContainer.tsx
src/components/buttons/ListBtn.tsx
src/components/buttons/MoreBtn.tsx
src/components/inputs/MenuBox.tsx
src/components/layouts/Header.tsx

- [LOOM](https://www.loom.com/share/5136f42674844ddab1bdbbfbe08d4e28)

OUT-1103, OUT-1100 Add Menu to access Manage Templates page from Task Board

---

src/app/manage-templates/ui/TemplateBoard.tsx
src/app/manage-templates/ui/TemplateForm.tsx
src/app/ui/MenuBoxContainer.tsx
src/components/buttons/ListBtn.tsx
src/components/buttons/MoreBtn.tsx
src/components/cards/CommentCard.tsx
src/components/inputs/MenuBox.tsx
src/components/layouts/ConfirmDeleteUI.tsx
src/components/layouts/Header.tsx

- [LOOM](https://www.loom.com/share/6c08cf0593824678ab25574d373c7ec0)

OUT-1061 | Implement functional Edit Template modal

---

src/app/manage-templates/actions.ts
src/app/manage-templates/page.tsx
src/app/manage-templates/ui/TemplateBoard.tsx
src/hoc/RealtimeTemplates.tsx
src/redux/features/templateSlice.tsx
src/types/interfaces.ts
src/utils/validateTimeStamp.ts

- [LOOM](https://www.loom.com/share/37ee2e69a032437bb9c24ddf052e7d44)

OUT-1102 | Add real-time functionality for Manage Page

---

src/app/manage-templates/ui/TemplateForm.tsx

OUT-1127 | OUT-1131 | Change copies for template modal headers

---

src/app/detail/ui/Sidebar.tsx

- [LOOM](https://www.loom.com/share/d326f1af2d504053900ed4cdc477f105)

OUT-1151 | Task details properties reposition once loaded

---

src/components/inputs/Selector.tsx

OUT-1107 | Fix border radius issues with all Selectors

---

src/app/detail/ui/ActivityWrapper.tsx
src/components/inputs/CommentInput.tsx

OUT-1165 | Fix comment behavior on task description page

---

src/utils/sortTask.ts

[Screencast from 2024-12-19 18-02-48.webm](https://github.com/user-attachments/assets/1749eb0b-55f3-4291-965e-3b0d5c40a393)

OUT-1093 | Fix tasks jumping around on hover

---

src/app/_fetchers/AssigneeFetcher.tsx
src/app/api/core/models/User.model.ts
src/app/client/page.tsx
src/app/detail/[task_id]/[user_type]/page.tsx
src/app/ui/NewTaskForm.tsx
src/app/ui/TaskBoard.tsx
src/components/inputs/Selector.tsx
src/components/layouts/Header.tsx
src/hoc/ClientSideStateUpdate.tsx
src/utils/previewMode.ts

OUT-1163 | Change create task modal behavior

---

src/components/inputs/MenuBox.tsx

OUT -1178 | Adjust corner radius of delete button and manage templates button

---

src/app/ui/TaskBoard.tsx

OUT-1179 | Replace 1/1 or X/X on top of each section in board and list view with just the number of tasks

---

package.json
supabase/.gitignore
supabase/config.toml
yarn.lock

OUT-1159 | Implement Supabase, Supabase storage and Supabase Realtime in local environment

---

src/utils/getTimeDifference.ts

- [LOOM](https://www.loom.com/share/0985f643fec044e1aa8df817b5138c1b)

OUT-1201 | Comment timestamp and Deleted Users in an archived task

---

src/app/api/activity-logs/schemas/WorkflowStateUpdatedSchema.ts
src/app/api/activity-logs/services/activity-logger.service.ts
src/app/api/tasks/tasks.helpers.ts
src/app/api/tasks/tasks.logger.ts
src/app/api/tasks/tasks.service.ts
src/app/detail/ui/ActivityLog.tsx

OUT-1203 | OUT-1190 | API: Add TasksActivityLogger and implement activity log for WorkflowState updated

---

src/app/detail/ui/ActivityLog.tsx
src/app/detail/ui/DotSeparator.tsx

OUT-1189 | OUT-1209 | UI: Add support for Workflow State updated & Refactor old Activity Log implementation

---

src/app/api/tasks/tasks.logger.ts

- [LOOM](https://www.loom.com/share/44642977c11f4ad1ba76034acd56b80f)

OUT-1211 | Do not log title change in activity feed if only leading and trailing whitespaces are changed

---

package.json
src/app/api/activity-logs/services/activity-log.service.ts
src/cmd/fill-activity-logs/fillTaskAssigned.ts
src/cmd/fill-activity-logs/fillTaskCreated.ts
src/cmd/fill-activity-logs/fillWorkflowStateUpdated.ts
src/cmd/fill-activity-logs/index.ts

OUT-1221 | OUT-1222| Backfill "Task assigned" and "Workflow state updated" activity logs

---

src/app/api/tasks/tasks.service.ts

OUT-1228 | CU status change not added to activity feed

---

src/app/api/notification/validate-count/validateCount.service.ts

OUT-1236 | Modify validate-count route to account for previously archived tasks in Production

---

src/app/ui/NewTaskForm.tsx
src/components/inputs/Selector.tsx
src/redux/features/createTaskSlice.ts
src/utils/trimTags.ts

- [LOOM](https://www.loom.com/share/e7c82e2dabe24eecad9a5e22ad5307ff)

OUT-1239 | Apply template should append template content instead of replacing

---

src/components/cards/CommentCard.tsx

OUT-1242 | Reduce spacing of dots in comment blocks

---

.env.example
package.json
src/cmd/serve-embedded/index.ts
yarn.lock

[Screencast from 2025-01-09 16-24-57.webm](https://github.com/user-attachments/assets/9e46c251-fcba-45e1-9508-cbc60e2c80c7)

OUT-1248 | Implement dev mode for Copilot Dashboard

---

src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/ArchiveWrapper.tsx
src/app/detail/ui/DetailAppBridge.tsx
src/app/detail/ui/MenuBoxContainer.tsx

OUT-1256 | Implement "Archive task" & "Delete task" for Task details page

---

src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/ResponsiveStack.tsx
src/app/detail/ui/Sidebar.tsx
src/components/inputs/DatePickerComponent.tsx
src/components/inputs/Selector-WorkflowState.tsx
src/components/inputs/Selector.tsx
src/types/interfaces.ts
src/utils/iconMatcher.tsx

- [LOOM](https://www.loom.com/share/bdb3f9d0dc364a61915f62e07ca308f7)

OUT-1271 | Implement new mobile design for task details page.

---

src/app/detail/ui/TaskEditor.tsx
src/app/detail/ui/styledComponent.tsx
src/app/manage-templates/ui/TemplateBoard.tsx
src/app/manage-templates/ui/TemplateForm.tsx
src/app/ui/Modal_NewTaskForm.tsx
src/components/cards/CommentCard.tsx
src/theme/theme.ts
src/types/theme.d.ts

OUT-1266 | Adjust modal grey out color

---

src/types/common.ts

fix(OUT-1288) : type change for customFields in ClientResponseSchema

---

src/app/api/users/users.service.ts

OUT-1267 | Assignee dropdown should prioritize current user at the top of list

---

src/app/detail/ui/TaskEditor.tsx

- [LOOM](https://www.loom.com/share/92958dedac2141ffbb4d6c348a301d73)

OUT-1316 | Title changes are not saved, glitchy behavior

---

src/app/detail/ui/Sidebar.tsx
src/app/detail/ui/TaskEditor.tsx
src/components/inputs/Autocomplete.tsx
src/components/inputs/Selector.tsx
src/theme/theme.ts
src/types/theme.d.ts

- [LOOM](https://www.loom.com/share/eb8596a5680648bd8310006751cf1c4a)

OUT-1305 | Enable clicking on sidebar to reassign a task

---

src/app/detail/ui/ActivityLog.tsx

OUT-1306 | When task reassignment takes place create Reassignment Activity Log

---

src/app/detail/ui/Sidebar.tsx
src/utils/shouldConfirmBeforeReassign.ts

- [LOOM](https://www.loom.com/share/02e0512682c344fc99f75506c01d1763)

OUT-1310 | Implement Confirmation Modal for task reassigned to Client & Company

---

src/app/api/tasks/task-notifications.service.ts

[Screencast from 2025-01-27 16-00-43.webm](https://github.com/user-attachments/assets/2dea4488-73fc-4d8e-90b7-afd84bbe9a38)

OUT-1325 | Fix IU notifications not getting deleted while reassigning completed task

---

src/app/api/notification/notification.helpers.ts

Just removed an over explanatory sentence

minor notification copy update

---

src/hoc/RealTime.tsx

- [LOOM](https://www.loom.com/share/45ecf87e334342a28167abe5fbdd800b)

OUT-1340 | Tasks do not disappear in real-time when task reassigned

---

src/app/detail/[task_id]/[user_type]/page.tsx
src/components/cards/CommentCard.tsx
src/components/layouts/FilterBar.tsx

OUT-1335, OUT-1243  | Adjust top line above task title

---

src/components/cards/TaskCard.tsx
src/hoc/RealTime.tsx

- [LOOM](https://www.loom.com/share/abbba6cc80d442e4bb07489e60288a52)

OUT-1346  | Tasks are not reassigned in realtime from CU -> company

---

src/hoc/RealTime.tsx

hotfix: Verbose short circuit to prevent any and all unrelated tasks from rendering on realtime UPDATE

---

package.json
src/cmd/delete-duplicate-notifications/index.ts

Optimization: Add script to force delete duplicate notifications

---

src/app/api/tasks/tasks.service.ts
src/jobs/notifications/delete-task-notifications.ts
src/jobs/notifications/index.ts
src/jobs/notifications/send-task-create-notifications.ts

Notification was also deleted when task was deleted

OUT-1376 | Implement task queue for notifications deletion

---

src/app/api/comment/comment.controller.ts
src/app/api/comment/comment.service.ts

[Screencast from 2025-02-11 13-14-53.webm](https://github.com/user-attachments/assets/5682a67c-3580-4b0d-9379-734eb57d6b27)

OUT-1386 | Add API endpoint to update comments

---

src/components/inputs/Selector.tsx

- By doing the above mentioned steps, we actually update the state of the placement only when it is required and not in every render/resize which was leading to an infinite rendering.   
- [LOOM](https://www.loom.com/share/0eeee5df463643aa8f04196dbf3f1de3)

OUT-1396 | Assignee selector glitches up and down when active

---

package.json
src/app/api/activity-logs/services/activity-log.service.ts
src/app/api/core/services/policies.service.ts
src/app/detail/[task_id]/[user_type]/actions.ts
src/components/buttonsGroup/EditCommentButtons.tsx
src/components/cards/CommentCard.tsx
src/components/inputs/CommentInput.tsx
src/utils/isTapwriteContentEmpty.ts

- [LOOM](https://www.loom.com/share/a902904adb5349c9912187c6f3388531)

OUT-1387, OUT-1388 | Update comment UI

---

src/components/buttons/ListBtn.tsx
src/components/cards/CommentCard.tsx
src/components/inputs/MenuBox.tsx

OUT-1415 | Adjust height of kebab menu options to match Figma

---

src/app/detail/ui/TaskEditor.tsx
src/app/tapwrite.css

- [LOOM](https://www.loom.com/share/b0da80c28dfb4dd49d4ad36bcc460069)

OUT-1427 | Image should have cursor pointer to indicate it can be opened

---

package.json
src/components/cards/CommentCard.tsx
src/components/inputs/CommentInput.tsx
yarn.lock

- [LOOM](https://www.loom.com/share/45c46fc480024c7b8cdfb875cc936fc0)

OUT-1431 , OUT-1446 | Pressing enter/return does not do anything on mobile

---

src/app/api/core/services/policies.service.ts
src/app/api/scrap-medias/scrap-medias.service.ts
src/components/cards/CommentCard.tsx

- [LOOM](https://www.loom.com/share/4cb5bf4c4fe24559ab0c029a42332bce)

OUT-1444, OUT-1443 | CU cannot edit comment, CU cannot upload images to a comment, loads forever

---

src/app/detail/ui/ImagePreviewModal/ImageRenderer.tsx

[Screencast from 2025-02-20 16-22-56.webm](https://github.com/user-attachments/assets/039ed34e-6b43-45e5-9285-23fca0304197)

OUT-1442 | Remove image fade in transition on image preview

---

src/components/cards/CommentCard.tsx
src/components/inputs/MenuBox.tsx

- [LOOM](https://www.loom.com/share/d98804b16c3e4f438318cc9b4610a810)

OUT-1417 | Kebab menu disappears when cursor leaves comment box

---

src/app/detail/ui/ImagePreviewModal/index.tsx

OUT-1448 | Replace loading spinner with the one we use for app

---

package.json
yarn.lock

OUT-1425 | Change image border radius from 5px to 2px

---

src/app/api/users/client/route.ts
src/app/api/users/users.controller.ts
src/app/api/users/users.service.ts
src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/ActivityLog.tsx
src/app/detail/ui/Sidebar.tsx
src/components/cards/CommentCard.tsx

- [LOOM](https://www.loom.com/share/818a6b942faf46a8ab98e36e262695e4)

OUT-1406 | 'Deleted User' shows in place of user name in activity log and properties

---

src/components/cards/CommentCard.tsx

- [LOOM](https://www.loom.com/share/cf73c594597c46eba24095e31082e088)

OUT-1451 | Fix new comment animation

---

prisma/migrations/20250227112916_add_optional_initiator_type_to_comments/migration.sql
prisma/schema/comment.prisma
src/app/api/comment/comment.controller.ts
src/app/api/comment/comment.service.ts
src/app/api/comment/route.ts
src/app/api/tasks/tasks.service.ts

https://github.com/user-attachments/assets/ecf96483-0244-4502-8dc4-824eab08ddfa

OUT-1458 | OUT-1459 | OUT-1460 | OUT-1461 | Add endpoints to get replies, create reply, edit reply & delete reply

---

package.json
yarn.lock

- Please perform vigorous testing on preview app before merging.

OUT-1409 | RangeError: Position 91 outside of fragment (<paragraph, paragraph, uploadAttachment, uploadAttachment>)

---

src/cmd/serve-embedded/index.ts
src/constants/domains.ts
src/hooks/app-bridge/useActionsMenu.tsx
src/hooks/app-bridge/useBreadcrumbs.tsx
src/hooks/app-bridge/usePrimaryCta.tsx
src/hooks/app-bridge/useSecondaryCta.tsx
src/utils/CopilotAPI.ts
yarn.lock

chore: update domain

---

package.json
yarn.lock

OUT-1489 | sdk and domain update for tasks app

---

src/components/AttachmentLayout.tsx
src/components/buttonsGroup/SubmitCommentButtons.tsx
src/components/inputs/CommentInput.tsx
src/components/inputs/ReplyInput.tsx

- [LOOM](https://www.loom.com/share/284212b7da6a464b9da966928582070f)

OUT-1501 | User can submit comments even when the attachment is being uploaded.

---

src/components/cards/CommentCard.tsx
src/components/cards/ReplyCard.tsx

- [LOOM](https://www.loom.com/share/1eb9e9cb57c04ead960737175c2d3893)

OUT-1505 | Optimistic updates on deleting replies on view all mode

---

src/components/atoms/OverlappingAvatars.tsx

HOTFIX : overlapping avatars design issue

---

src/app/detail/ui/ActivityWrapper.tsx

- [LOOM](https://www.loom.com/share/8603bd327b8643e984e90ea78d4a9306)

OUT-1486 | UI - Support redirection and scroll to thread reply on Notification CTA Click

---

src/app/detail/ui/ActivityLog.tsx
src/app/detail/ui/Comments.tsx
src/components/atoms/CopilotAvatar.tsx
src/theme/theme.ts
src/types/theme.d.ts

OUT-1508, OUT-1510 | Deleted state icon for comments has wrong background and border color

---

src/app/api/comment/comment.service.ts
src/components/cards/CommentCard.tsx

https://github.com/user-attachments/assets/cffc54a8-27f3-4d4f-82ea-5375cf2289c9
- Comment deletion behavior (thoroughly tested to avoid regressions)

OUT-1509 | Deleted parent comment should be removed from UI if all replies are deleted

---

src/components/atoms/OverlappingAvatars.tsx
src/components/cards/CommentCard.tsx
src/components/cards/ReplyCard.tsx

OUT-1519 | Reply content is not vertically centered within contianer

---

src/app/tapwrite.css

OUT-1518 | Reduce height of active comment text box

---

package.json
yarn.lock

OUT-1520 | Change text color of task description and comments to text-primary

---

src/components/cards/ListViewTaskCard.tsx

- [LOOM](https://www.loom.com/share/3e36d049ee3343629901087144eecdee) 
- List view layout in different screen sizes for assignee of a task.

OUT-1545 | Client information occasionally not loading

---

src/components/cards/ReplyCard.tsx

OUT-1544 | Update delete reply modal

---

sentry.client.config.ts
sentry.server.config.ts

OUT-1563 | Prevent cascading "Fetch failed" errors from being reported to Sentry

---

src/components/cards/CommentCard.tsx
src/components/cards/ReplyCard.tsx

- [LOOM](https://www.loom.com/share/9226c8309bfa4bd1929d4964d29600e6)
- Comment/replies layout

OUT-1500 | Comments/Replies layout issue for small screen size (350px)

---

src/app/api/tasks/tasks.controller.ts
src/app/api/tasks/tasks.service.ts

https://github.com/user-attachments/assets/c56b7157-4016-4f61-bdbf-505ef4e75b35

OUT-1553: Implement GET all subtasks endpoint

---

src/app/api/tasks/tasks.service.ts
src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/NewTaskCard.tsx
src/app/detail/ui/Subcomments.tsx
src/app/detail/ui/Subtasks.tsx
src/app/detail/ui/TaskCardList.tsx
src/app/detail/ui/styledComponent.tsx
src/app/ui/TaskBoard.tsx
src/icons/add-gray.svg
src/types/common.ts
src/types/dto/tasks.dto.ts
src/utils/getCardHref.ts

- [LOOM](https://www.loom.com/share/487c3446f67b4196bd17e3ae52af9bd0)

OUT-1552 , OUT-1561 | Implement Subtasks List in Task Details UI

---

src/components/cards/ListViewTaskCard.tsx

OUT-1579 | Task ID is shown with ellipse in List view

---

src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/Subtasks.tsx

case where there are no subtasks for a given task :

OUT-1586 | subtask creation button and header removal in client view.

---

src/app/detail/ui/Subtasks.tsx

- [LOOM](https://www.loom.com/share/04d2761ab96647889884bf6d0a34fd04)

OUT-1585 | implement real-time functionality for sub-tasks

---

src/app/api/tasks/subtasks.service.ts
src/app/api/tasks/tasks.service.ts

- Delete parent task
- Delete a part of a task chain
Link: https://drive.google.com/file/d/1eypWRkPCulclYT76JrHyAKlLvKwKUZAX/view?usp=sharing

OUT-1572 | Implement cascading deletes for sub-tasks

---

src/app/detail/ui/Subtasks.tsx

OUT-1590 | Prevent "Create Subtask" button from flickering

---

src/app/api/tasks/all/route.ts
src/app/api/tasks/tasks.controller.ts
src/app/api/tasks/tasks.service.ts
src/app/client/page.tsx
src/app/page.tsx
src/hoc/ClientSideStateUpdate.tsx
src/hoc/RealTime.tsx
src/redux/features/taskBoardSlice.tsx

- fixed issue of sub tasks popping up in task board for iu and clients.
- only those tasks whose parent id are un-accesible to the client/iu are made to be popped up in the task board in real time.
- [LOOM](https://www.loom.com/share/129d9a1a0a60456282a81a84789eee5a)

OUT-1584 | Fix Realtime Behavior

---

src/app/detail/ui/ImagePreviewModal/index.tsx

OUT-1455 | TypeError: n.includes is not a function

---

src/app/detail/ui/NewTaskCard.tsx
src/components/inputs/DatePickerComponent.tsx
src/components/inputs/Selector-WorkflowState.tsx
src/components/inputs/Selector.tsx
src/utils/optimisticTaskUtils.ts

- [LOOM](https://www.loom.com/share/22354818930e43cbbbfc7c239762adb5) 
- Check behavior, designs on other form components' buttons (OUT-1611).

OUT-1602, OUT-1610, OUT-1611 | Undefined and invalid date is momentarily shown when adding sub-task with due date 

---

src/app/api/tasks/subtasks.controller.ts

OUT-1622 | Limit to 1 layer of subtasks

---

src/app/api/tasks/tasks.controller.ts
src/app/api/tasks/tasks.service.ts
src/app/detail/ui/Subtasks.tsx

https://github.com/user-attachments/assets/30b10dd5-8459-4c2d-99be-a1f4402489c7

OUT-1639 | Users not being able to view subtasks; Subtasks cannot be created

---

package.json
src/app/_fetchers/AssigneeFetcher.tsx
src/app/api/users/users.service.ts
yarn.lock

OUT-1636 | Assignee icons periodically do not load

---

src/app/detail/ui/TaskCardList.tsx
src/components/inputs/DatePickerComponent.tsx

[Screencast from 04-16-2025 11:33:13 AM.webm](https://github.com/user-attachments/assets/6c129321-2d1a-4d0a-bbc4-5ff036d41322)

OUT-1640 | Remove hover states for due date and assignee in list view for CU

---

src/app/detail/ui/Subtasks.tsx
src/app/detail/ui/TaskCardList.tsx

- [LOOM](https://www.loom.com/share/d078699f31b246119b86055d19818668)

OUT-1627 | Due date does not update in realtime on subtask list view component

---

src/app/detail/ui/NewTaskCard.tsx

- [LOOM](https://www.loom.com/share/6414254f0e434cc480a0f55e907dcff8)

OUT-1630 | Make task title box active after creating subtask

---

src/app/_fetchers/AllTasksFetcher.tsx
src/hooks/useFilter.tsx
src/lib/realtime.ts
src/types/dto/tasks.dto.ts

OUT-1641 | Make task ids searchable

---

src/app/(home)/actions.ts
src/app/_fetchers/AllTasksFetcher.tsx
src/app/api/tasks/tasks.service.ts
src/hoc/ClientSideStateUpdate.tsx
src/hoc/RealTime.tsx
src/hooks/useFilter.tsx
src/lib/realtime.ts
src/redux/features/taskBoardSlice.tsx
src/types/dto/tasks.dto.ts

https://github.com/user-attachments/assets/1b7190f2-9fe6-4c22-864c-401170ba5693

OUT-1625 | Realtime issue when parentTask is updated on disjoint tasks.

---

package.json
src/app/api/tasks/public/public.controller.ts
src/app/api/tasks/public/public.serializer.ts
src/app/api/tasks/public/route.ts
src/app/api/tasks/tasks.controller.ts
src/app/api/tasks/tasks.service.ts
src/constants/public-api.ts
src/types/common.ts
yarn.lock

OUT-1672 | Add support for exposing list tasks API

---

src/app/client/page.tsx

- [LOOM](https://www.loom.com/share/3774153b91234c7999b900a73aca3c41)

OUT-1686 | Task templates not listing for certain users

---

src/app/api/tasks/public/public.controller.ts
src/app/api/tasks/public/public.dto.ts
src/app/api/tasks/public/public.serializer.ts
src/app/api/tasks/public/route.ts
src/app/api/tasks/tasks.service.ts
src/constants/tasks.ts
src/utils/dateHelper.ts

OUT-1670 | Add support for exposing create task API

---

src/app/api/tasks/tasks.helpers.ts
src/app/api/tasks/tasks.service.ts
src/types/webhook.ts
src/utils/CopilotAPI.ts

https://github.com/user-attachments/assets/cf53d46b-747b-4b82-8489-fc77ee9a0d86

OUT-1680 | Add support for dispatching webhook request for required event names

---

src/app/api/tasks/tasks.helpers.ts

- **fix(OUT-1680): safer handling for archived status**

OUT 1680 roj

---

src/app/api/tasks/public/public.dto.ts
src/app/api/tasks/public/public.serializer.ts
src/app/api/tasks/tasks.service.ts
src/app/ui/Modal_NewTaskForm.tsx
src/app/ui/NewTaskForm.tsx
src/redux/features/createTaskSlice.ts
src/types/dto/tasks.dto.ts

https://github.com/user-attachments/assets/263464ae-fcd2-4b9e-863c-832b5def1f6f
https://github.com/user-attachments/assets/48f70da8-9d4e-4f6c-ae08-87601d74b231

OUT-1694 | OUT-1696 | Implement templateId + archivedBy (UI & API)

---

src/app/api/tasks/public/public.serializer.ts
src/app/api/tasks/tasks.service.ts
src/types/dto/tasks.dto.ts

- [LOOM](https://www.loom.com/share/d6a6b71ab2274b1fbc79145c52847695)

OUT-1709 | Public update tasks assigneeId and assigneeType validation.

---

src/app/api/tasks/tasks.service.ts
src/types/common.ts
src/utils/CopilotAPI.ts

https://github.com/user-attachments/assets/df0289de-de84-4983-b77a-440dd88f5a62

OUT-1710 | Missing createdBy support for creating tasks through public API.

---

src/app/api/tasks/tasks.service.ts

- [LOOM](https://www.loom.com/share/ee2cb3f36bd4407db449a6fcf01ccb5c)

OUT-1721 | Template not applying to task

---

src/app/detail/ui/Subtasks.tsx

- [LOOM](https://www.loom.com/share/e3b6936456734edebe24d313ece27335)

OUT-1728 | Archive status on subtask list does not change in realtime

---

src/app/api/tasks/public/public.controller.ts
src/app/api/tasks/tasks.service.ts

- [LOOM](https://www.loom.com/share/dc7ebf6dba1748729f94c1bf27bf965d)

OUT-1737 | User should be able to retrieve a deleted task

---

prisma/migrations/20250513130624_add_individual_user_id_columns_to_tasks/migration.sql
prisma/migrations/20250514082409_add_individual_user_id_columns_in_tasks/migration.sql
prisma/schema/task.prisma
src/cmd/load-testing/load-testing.service.ts

OUT-1729 | Modify Schema of Tasks to include internalUserId, clientId & companyId

---

prisma/migrations/20250527121210_add_constraints_for_user_id_columns_in_tasks/migration.sql

-[x] Add DB constraints to enforce proper combination of userId fields

OUT-1790 | Add DB constraints to enforce proper combination of userId fields

---

prisma/migrations/20250528073853_enforce_user_id_on_assignee_id/migration.sql

… mapping
-- If assigneeType is internalUser, enforce assigneeId + internalUserId
-- If assigneeType is client, enforce assigneeId + clientId + companyId
-- If assigneeType is company, enforce assigneeId + companyId
https://github.com/user-attachments/assets/aea024d9-1de8-49de-b64d-d9ef2a1ebee5

OUT-1812 | Add DB constraint to enforce AT LEAST ONE userId column to be present for non-null assigneeID

---

src/app/detail/ui/TaskCardList.tsx

hotfix : placeholder typo for assignee selector in list view task cards. 

---

src/hooks/useFilter.tsx

- [LOOM](https://www.loom.com/share/da12c8fc15d946ce8a0ca383cdd6b811)

OUT-1818 | The search function in the Task app is currently not working as expected

---

package.json
src/components/inputs/CopilotSelector.tsx
yarn.lock

OUT-1868 | Bump copilot-design-system version and apply relevant changes

---

src/lib/realtime.ts

HOTFIX : Reassignment out of scope for client 

---

src/app/api/notification/validate-count/validateCount.service.ts
src/types/common.ts
src/utils/CopilotAPI.ts

https://github.com/user-attachments/assets/24b6e2b1-7f84-4bde-a1e1-7bbd8c7ce5e7

OUT-1874 | Tasks Notifications - number keeps incrementing for a CU

---

src/app/detail/ui/Sidebar.tsx
src/app/detail/ui/TaskCardList.tsx

- [LOOM](https://www.loom.com/share/c494536ff6e7413592e8bebc9d6f844a)

OUT-1910 | Sub task list's assignee is change but the avatar is not changing on real time.

---

src/app/ui/NewTaskForm.tsx

OUT-1948 | Fix selected assignee text color

---

src/app/detail/ui/NewTaskCard.tsx
src/app/detail/ui/Sidebar.tsx
src/app/detail/ui/TaskCardList.tsx
src/app/ui/NewTaskForm.tsx
src/components/inputs/CopilotSelector.tsx

- [LOOM](https://www.loom.com/share/d0d8835f650f401888a2e52ade1fb73a)

OUT-1944, OUT-1947 | Noticeable delay when changing from assignee→no assignee→assignee

---

src/app/detail/ui/Subtasks.tsx
src/app/detail/ui/TaskCardList.tsx

- [LOOM](https://www.loom.com/share/39df49d174a54198a4a9f961ab9eb67f)

OUT-1996 | Tasks app issue in Company details view

---

.gitignore
src/cmd/backfill-missed-emails/index.ts
src/utils/crypto.ts

OUT-2009 | Backfill missed task email notifications for incomplete tasks

---

src/app/api/tasks/tasks.service.ts
src/app/detail/ui/NewTaskCard.tsx
src/hoc/RealTime.tsx

- [LOOM](https://www.loom.com/share/60e51548a40a4231aa56dd7567c09e2f)
- Do not merge this in main, only promote this to production. Need to apply this PR separately in feature/m15 milestone.

OUT-1999 | CRM Task details view subtask issues.

---

src/app/detail/ui/ActivityWrapper.tsx
src/utils/optimisticCommentUtils.ts

OUT-1992: Triage bug related to zod

---

src/app/api/tasks/tasks.service.ts
src/app/detail/ui/NewTaskCard.tsx
src/app/detail/ui/TaskCardList.tsx
src/components/atoms/TaskMetaItems.tsx
src/hoc/RealTime.tsx

- [LOOM](https://www.loom.com/share/a7313bfdeba24b70ac1328493fcd49f2)

OUT-1999 (for milestone 15) : CRM Task details view subtask issues.

---

src/app/api/notification/notification.service.ts

https://github.com/user-attachments/assets/3321d586-d9ed-40be-b01b-21d3e9790465

OUT-2046 | OUT-2035 | Task count doesn't increase/decrease with the correct number

---

src/app/detail/ui/Sidebar.tsx

[Loom](https://www.loom.com/share/7770f0ece02e415f8d59725ed87f0e24?sid=7a0c9b76-133e-4acd-9871-47c1eb0159b8)

OUT-2054: Delay on changing assignee from task details sidebar

---

src/cmd/load-testing/index.ts
src/cmd/load-testing/load-testing-v2.service.ts
src/types/common.ts

OUT-2045 | Seed companies for Load Testing workspace

---

src/cmd/load-testing/load-testing-v2.service.ts

OUT-2099 | Fix CopilotAPI call flow in Load Testing Service

---

src/components/inputs/CopilotSelector.tsx

- [LOOM](https://www.loom.com/share/8d7db0f8e1b4403fb5e7bc63792c2cdb)

OUT-2140 | Reassignment is not possible

---

src/app/api/comment/comment.service.ts

https://github.com/user-attachments/assets/595c4960-d288-404e-a25c-9275573ade5f

OUT-2103 | Realtime not working for replies

---

src/app/api/tasks/tasks.service.ts

- [LOOM](https://www.loom.com/share/ad90109f24424ad6b0eccdd4e61f9c83)

OUT-2159 | Transaction error while deleting subtasks

---

src/app/ui/TaskBoard.tsx
src/components/atoms/TaskMetaItems.tsx
src/components/cards/CardDragLayer.tsx
src/components/cards/TaskCard.tsx
src/components/inputs/CopilotSelector.tsx
src/components/inputs/DatePickerComponent.tsx
src/components/inputs/Selector-WorkflowState.tsx
src/components/layouts/DueDateLayout.tsx
src/hoc/CustomLink.tsx
src/theme/theme.ts
src/types/theme.d.ts
src/utils/dueDateFormatter.ts

-[LOOM](https://www.loom.com/share/5bf8cff6a6ae49b794ecf92e4c073297)

OUT-2130, OUT-2133, OUT-2135 | Add support for interactivity in task cards on board view.

---

src/app/detail/ui/ClientDetailAppBridge.tsx

I am using the check icon instead of the plus icon for the app bridge header CU mark as done button.
- Dependencies on other PRs, any required changes in config/setup to test behaviour, or links to external documents, threads, etc -- if any of them are required
- An overview of components behaviour to be looked at for unintended breaks after the changes. This will make regression testing easier and efficient.

chore(OUT-2202): Use check icon for CU mark as done button

---

src/app/detail/ui/ClientDetailAppBridge.tsx
src/app/ui/VirtualizedTasksLists.tsx
src/components/buttons/GhostBtn.tsx

- [LOOM](https://www.loom.com/share/eecdd8c9b19d41b68815cb2b488bfb67)

OUT-2251, OUT-2252 | Unable to drag subtask on list view

---

src/app/ui/NewTaskForm.tsx
src/components/buttons/SelectorButton.tsx
src/components/inputs/DatePickerComponent.tsx
src/hoc/AppMargin.tsx

[Loom](https://www.loom.com/share/9f09013cc2f745f28dc0cccf06fc2586?sid=ece1de78-cf40-495e-b79d-8ef3fbde3341)

OUT-2265: Update the task creation modal

---

src/app/detail/ui/ClientDetailAppBridge.tsx
src/app/manage-templates/ui/TemplateForm.tsx
src/app/ui/NewTaskForm.tsx
src/components/buttons/SelectorButton.tsx
src/components/inputs/DatePickerComponent.tsx
src/hoc/AppMargin.tsx

[Loom](https://www.loom.com/share/9f09013cc2f745f28dc0cccf06fc2586?sid=cff21278-bcd5-4577-b788-2f0f2caee2d1)

OUT-2265: Update template create/edit modal

---

src/app/detail/ui/Sidebar.tsx
src/app/ui/NewTaskForm.tsx

OUT-2267: client visibility button in mobile view, due date icon padding

---

src/app/client/page.tsx
src/app/ui/NewTaskForm.tsx

[Loom](https://www.loom.com/share/216e774f5b5d4eaeb72fc225e0b59439?sid=724890ec-194e-4efe-98a8-a8efe2fca114)

OUT-2311: decode URI component before parsing

---

src/app/detail/ui/Sidebar.tsx

- [LOOM](https://www.loom.com/share/3f1e8f0c245d4badb56878737641db7b)

OUT-2341 | Hide mark as done button for CU viewers on task details page

---

src/app/ui/NewTaskForm.tsx

[Loom](https://www.loom.com/share/a7903a08ae6745e29f2393804b25226d?sid=31cd3020-74c1-412f-8b73-1075dd0f8968)

OUT-2340: Task due date in query parameters is set as day before specified date

---

src/types/common.ts

OUT-2344 | Customer faced intermittent Something went wrong error

---

package.json
src/app/_cache/AssigneeCacheGetter.tsx
src/app/_cache/AssigneeCacheSetter.tsx
src/app/_cache/forageStorage.ts
yarn.lock

- [LOOM](https://www.loom.com/share/e0a15ca7c0b84f20a5d3b188e46d0538)

OUT-2348 | Tasks app not loading for CU in workspace

---

src/app/api/tasks/tasks.service.ts
src/app/detail/[task_id]/[user_type]/page.tsx
src/app/detail/ui/Sidebar.tsx
src/app/ui/TaskBoard.tsx
src/components/layouts/FilterBar.tsx
src/hooks/useFilter.tsx
src/types/objectMaps.ts
src/utils/previewMode.ts

Overall test
[Loom](https://www.loom.com/share/84c1368eea0a42a6ba2d294545eba42e?sid=2ab9be90-3ea0-42a1-93a7-ae10939d7894)
Default assignee for task creation modal test criteria
[Loom](https://www.loom.com/share/59ea279e73b94eed96027bec93fabdb0?sid=27ec2798-830c-4ce5-a901-55837311fea6)

OUT-2330: Filter by type changes in CRM view

---

src/app/api/notification/notification.service.ts

HOTFIX:notification count issue on comments

---

src/app/api/notification/validate-count/validateCount.service.ts

HOTFIX: validate notification raw query

---

src/lib/realtime.ts

OUT-2431: Shared task disappear when hover on the card for companies

---

prisma/migrations/20251006130120_add_user_ids_in_view_settings_table/migration.sql
prisma/schema/viewSetting.prisma
src/app/api/view-settings/viewSettings.service.ts
src/types/common.ts

[Loom](https://www.loom.com/share/8f77416d9fc94a7283e6937065decf10?sid=2fcc7e58-0b84-4c00-bb35-2f5aeb45bea8)

OUT-2436: separate view setting for CRM view and task-app view

---

src/app/api/tasks/tasks.service.ts

isBefore() function of dayjs was returning true for few hours difference.

OUT-2457: Updated due date not persisting on tasks
