prisma/migrations/20240509154310_add_deleted_at_to_all_tables/migration.sql, prisma/schema.prisma, src/lib/db.ts, src/lib/prismaExtensions.ts
- [OUT-358 | API - Soft delete records in database](https://linear.app/copilotplatforms/issue/OUT-358/api-soft-delete-records-in-database)
- Prisma Client Extensions [docs](https://www.prisma.io/docs/orm/prisma-client/client-extensions)
- `$use` is used everywhere online - even Prisma doc's middlewares example uses it, but it is deprecated - use client extensions instead.
=> OUT-358 | API - Soft delete records in database

src/app/manage-templates/ui/TemplateForm.tsx, src/app/ui/NewTaskForm.tsx, src/redux/features/templateSlice.tsx
- [If I start editing a template, then hit Escape (to close), then click New Template, it loads the template I was editing](https://linear.app/copilotplatforms/issue/OUT-419/if-i-start-editing-a-template-then-hit-escape-to-close-then-click-new)
- [When I load a template, the assignee should not change](https://linear.app/copilotplatforms/issue/OUT-417/when-i-load-a-template-the-assignee-should-not-change)
- [When editing a template, the modal should say Edit Template](https://linear.app/copilotplatforms/issue/OUT-418/when-editing-a-template-the-modal-should-say-edit-template)
- [LOOM](https://www.loom.com/share/9f65ca87083949cb96333505d5a6800d)
=> OUT-419 If I start editing a template, then hit Escape (to close), then click New Template, it loads the template I was editing

src/app/ui/NewTaskForm.tsx, src/components/inputs/Selector.tsx
- [Typeahead not working for templates](https://linear.app/copilotplatforms/issue/OUT-435/typeahead-not-working-for-templates)
=> OUT-435 Typeahead not working for templates

src/app/ui/NewTaskForm.tsx, src/components/layouts/FilterBar.tsx, src/redux/features/taskBoardSlice.tsx, src/types/interfaces.ts
- [When I'm looking at Client Tasks and I hit Filter by, options should match](https://linear.app/copilotplatforms/issue/OUT-412/when-im-looking-at-client-tasks-and-i-hit-filter-by-options-should)
- [LOOM](https://www.loom.com/share/a519c30ecae442c8b207c1c6b32f5982)
=> OUT-412 When I'm looking at Client Tasks and I hit Filter by, options should match

src/app/ui/NewTaskForm.tsx, src/components/layouts/FilterBar.tsx
- [When My tasks filter is selected, and I hit New task, default assignee should be me](https://linear.app/copilotplatforms/issue/OUT-411/when-my-tasks-filter-is-selected-and-i-hit-new-task-default-assignee)
- [When I have a filter applied and I hit backspace to remove the filter, it chooses No Assignee but it shows me all tasks](https://linear.app/copilotplatforms/issue/OUT-431/when-i-have-a-filter-applied-and-i-hit-backspace-to-remove-the-filter)
- [LOOM](https://www.loom.com/share/2513e36244c143cb8a728da3f34897ab)
=> OUT-411 When My tasks filter is selected, and I hit New task, default assignee should be me

src/app/api/activity-logs/[id]/route.ts, src/app/api/attachments/attachments.controller.ts, src/app/api/tasks/tasks.controller.ts, src/app/api/users/users.controller.ts, src/app/api/view-settings/viewSettings.controller.ts, src/app/api/workflow-states/workflowStates.controller.ts, src/app/client/page.tsx, src/app/detail/[task_id]/[user_type]/page.tsx, src/app/layout.tsx, src/app/manage-templates/page.tsx, src/app/page.tsx
- [Turn off data caching](https://linear.app/copilotplatforms/issue/OUT-376/turn-off-data-caching)
Note: There seems to be bugs with NextJS regarding opting out of caching. `cache:no-store` only should work according to their docs, but it is unfortunately not working :(
=> OUT 376 Turn off data caching

src/app/ui/NewTaskForm.tsx, src/components/inputs/Selector.tsx
- [Assignee dropdown allows me to set assignee as empty text](https://linear.app/copilotplatforms/issue/OUT-475/assignee-dropdown-allows-me-to-set-assignee-as-empty-text)
- [Assignee autocomplete stops working after a space is inserted](https://linear.app/copilotplatforms/issue/OUT-476/assignee-autocomplete-stops-working-after-a-space-is-inserted)
=> OUT 475 | OUT-476 Issues with Assignee selector

src/components/cards/AttachmentCard.tsx, src/components/cards/ClientTaskCard.tsx, src/components/cards/TaskCard.tsx, src/types/constants.ts
- also introduced divider in CU view
- [Task card overflow issue](https://linear.app/copilotplatforms/issue/OUT-479/task-card-overflow-issue)
=> OUT-479 Task card overflow issue

src/app/api/core/types/tasks.ts, src/app/api/notification/notification.helpers.ts, src/app/api/notification/notification.service.ts, src/app/api/tasks/tasks.service.ts, src/utils/CopilotAPI.ts
- [OUT-387 | Task assigned to company should also trigger client notification](https://linear.app/copilotplatforms/issue/OUT-387/task-assigned-to-company-should-also-trigger-client-notification)
- [OUT-533 | As an internal user when I create a task assigned to myself I should not receive an in-product or email notification](https://linear.app/copilotplatforms/issue/OUT-533/as-an-internal-user-when-i-create-a-task-assigned-to-myself-i-should)
- Dependencies on other PRs, any required changes in config/setup to test behaviour, or links to external documents, threads, etc -- if any of them are required
=> OUT-387 | OUT-533 | Backend Notification Bugs

src/components/inputs/DatePickerComponent.tsx
- [Empty rounded & bordered div shows up when clicking on Due Date](https://linear.app/copilotplatforms/issue/OUT-515/empty-rounded-and-bordered-div-shows-up-when-clicking-on-due-date)
=> OUT-515 | Empty rounded & bordered div shows up when clicking on Due Date

src/app/detail/ui/Sidebar.tsx, src/components/inputs/DatePickerComponent.tsx, src/hoc/CustomScrollbar.tsx
- [LOOM](https://www.loom.com/share/5c22f6962ad247c89656a0ec13250f7d?sid=d47115a4-7d11-4ea8-a8bf-b78fb47bedeb)
=> OUT-518 Popper changing to top placement when there is not enough space.

src/app/ui/NewTaskForm.tsx, src/components/buttons/SecondaryBtn.tsx, src/components/inputs/Selector.tsx
- [input shifting down when opening assignee dropdown in new task dialog](https://linear.app/copilotplatforms/issue/OUT-552/input-shifting-down-when-opening-assignee-dropdown-in-new-task-dialog)
- [LOOM](https://www.loom.com/share/2568b2b1a3024d1297a94855b539e847)
=> OUT-552 input shifting down when opening assignee dropdown in new task dialog

src/app/detail/ui/Sidebar.tsx
- [No assignee shown as input in the textfield of autocomplete when the task is unassigned.](https://linear.app/copilotplatforms/issue/OUT-557/no-assignee-shown-as-input-in-the-textfield-of-autocomplete-when-the)
- [LOOM](https://www.loom.com/share/d384bb03d05f4bd0aa19a6a88ffb24ca)
=> OUT-557 No assignee shown as input in the textfield of autocomplete when the task is unassigned.

src/components/layouts/ConfirmDeleteUI.tsx
- [Delete confirmation modal not responsive on smaller screens](https://linear.app/copilotplatforms/issue/OUT-568/delete-confirmation-modal-not-responsive-on-smaller-screens)
- [LOOM](https://www.loom.com/share/8adcbef71c5e40b284bd9088c4b4ca18)
=> OUT-568 Delete confirmation modal not responsive on smaller screens

src/app/api/tasks/tasks.service.ts
=> OUT-579 Tasks that clients mark as done disappear

prisma/migrations/20240716021900_change_tasks_to_accept_date_string/migration.sql, prisma/migrations/20240716094430_change_tasks_to_accept_date_string/migration.sql, prisma/schema.prisma, src/app/detail/ui/Sidebar.tsx, src/app/ui/Modal_NewTaskForm.tsx, src/app/ui/NewTaskForm.tsx, src/components/cards/ClientTaskCard.tsx, src/components/cards/ListViewTaskCard.tsx, src/components/cards/TaskCard.tsx, src/components/inputs/DatePickerComponent.tsx, src/components/layouts/DueDateLayout.tsx, src/redux/features/createTaskSlice.ts, src/types/date.ts, src/types/dto/tasks.dto.ts, src/utils/dateHelper.ts
- [Due date seems wrong when you make it today](https://linear.app/copilotplatforms/issue/OUT-582/due-date-seems-wrong-when-you-make-it-today)
Use this SQL command to migrate your data to Date string
```sql
UPDATE "Tasks"
SET "dueDate" = SUBSTR("dueDate", 1, 10)
WHERE "dueDate" IS NOT NULL;
```
=> OUT-582 | Due date seems wrong when you make it today

src/app/api/notification/notification.service.ts, src/app/api/tasks/tasks.service.ts, src/app/api/users/users.service.ts, src/types/common.ts
- [OUT-572 | Only show clients where IU has access](https://linear.app/copilotplatforms/issue/OUT-572/only-show-clients-where-iu-has-access)
=> OUT-572 | Only show tasks and clients which IU has access to

src/app/client/page.tsx, src/app/client/ui/ClientTaskBoard.tsx, src/components/cards/ClientTaskCard.tsx, src/components/inputs/Selector.tsx, src/components/layouts/DueDateLayout.tsx
- [Empty state shows heading two times on Client end](https://linear.app/copilotplatforms/issue/OUT-594/empty-state-shows-heading-two-times-on-client-end)
- [Assignee name is shown with ellipse on Client end](https://linear.app/copilotplatforms/issue/OUT-595/assignee-name-is-shown-with-ellipse-on-client-end)
- [Fix Assignee alignment issue](https://linear.app/copilotplatforms/issue/OUT-596/fix-assignee-alignment-issue)
- [LOOM](https://www.loom.com/share/56bc1928e1924083847a97344eedc880)
=> OUT-594, OUT-595, OUT-596 Empty state shows heading two times on Client end

src/app/api/notification/notification.service.ts, src/app/api/tasks/tasks.service.ts
- [OUT-592 | In-product notifications don´t disappear for Clients after company task is deleted](https://linear.app/copilotplatforms/issue/OUT-592/in-product-notifications-don%C2%B4t-disappear-for-clients-after-company)
=> OUT-592 | In-product notifications don´t disappear for Clients after company task is deleted

src/components/cards/ClientTaskCard.tsx
- [CU redirects to task details page when clicking 'Mark done' button](https://linear.app/copilotplatforms/issue/OUT-626/cu-redirects-to-task-details-page-when-clicking-mark-done-button)
- [LOOM](https://www.loom.com/share/238e91c348e04ec8a1a466897fe2bd22)
=> OUT-626 CU redirects to task details page when clicking 'Mark done' button

src/app/ui/Modal_NewTaskForm.tsx
=> OUT-633 Make assignee a required field while creating task

src/app/api/notification/notification.helpers.ts, src/app/api/notification/notification.service.ts, src/app/api/tasks/tasks.service.ts
- [OUT-669 | In-product notification is not shown for IU when another IU completed the task](https://linear.app/copilotplatforms/issue/OUT-669/in-product-notification-is-not-shown-for-iu-when-another-iu-completed)
- [OUT-664 | Notification has an errant “for undefined”, for task completion on a task that was assigned to a company](https://linear.app/copilotplatforms/issue/OUT-664/notification-has-an-errant-for-undefined-for-task-completion-on-a-task)
=> OUT-669 | OUT-664 | In-product notification is not shown for IU when another IU completed the task

src/types/common.ts, src/utils/users.ts
- [OUT-643 | Search result shows duplicate records when searching with last name](https://linear.app/copilotplatforms/issue/OUT-643/search-result-shows-duplicate-records-when-searching-with-last-name)
=> OUT-643 | Search result shows duplicate records when searching with last name

src/app/api/notification/notification.helpers.ts, src/app/api/notification/notification.service.ts, src/app/api/tasks/tasks.service.ts
- [OUT-657 | CU does not receive email when IU assigns tasks to their company](https://linear.app/copilotplatforms/issue/OUT-657/)
- [OUT-655 | Button should say 'View task' in 'A task was assigned to you' email](https://linear.app/copilotplatforms/issue/OUT-655/)
- Email I received after feature was applied
=> OUT-657 | OUT-655 | CU does not receive email when IU assigns tasks to their company + Notification Email customization

src/app/api/users/users.service.ts
=> Hotfix: Increase client / company limit that is fed into filter

src/app/detail/ui/TaskEditor.tsx, src/app/ui/NewTaskForm.tsx
- [Able to create task by entering only blank spaces in Task name](https://linear.app/copilotplatforms/issue/OUT-703/able-to-create-task-by-entering-only-blank-spaces-in-task-name)
- [LOOM](https://www.loom.com/share/be1c0ac3b7a449a4b925fcfee5b8734d)
=> OUT-703 Able to create task by entering only blank spaces in Task name

src/components/buttons/FilterByAssigneeBtn.tsx, src/components/inputs/Selector.tsx, src/components/layouts/FilterBar.tsx, src/theme/theme.ts
- [Reduce spacing between assignees in drop-down on mobile experience](https://linear.app/copilotplatforms/issue/OUT-692/reduce-spacing-between-assignees-in-drop-down-on-mobile-experience)
- [First assignee is always shown as selected in Assignee drop-down](https://linear.app/copilotplatforms/issue/OUT-693/first-assignee-is-always-shown-as-selected-in-assignee-drop-down)
- [Search text does not reset to default state when switching between tabs](https://linear.app/copilotplatforms/issue/OUT-694/search-text-does-not-reset-to-default-state-when-switching-between)
- [LOOM](https://www.loom.com/share/02a6db3045684b8d84d12715b16e7905)
=> OUT-692, OUT-693, OUT-694 Reduce spacing between assignees in drop-down on mobile experience

src/app/api/core/types/tasks.ts, src/app/api/notification/notification.helpers.ts, src/app/api/notification/notification.service.ts, src/app/api/tasks/tasks.service.ts
- [OUT-696 | In-product notification content needs to be updated](https://linear.app/copilotplatforms/issue/OUT-696/in-product-notification-content-needs-to-be-updated)
=> OUT-696 | In-product notification content needs to be updated

src/app/error.tsx, src/components/layouts/Loader.tsx
- [wrapped a circular progress bar in a Box with styles to center the progress bar](https://linear.app/copilotplatforms/issue/OUT-727/loader-is-not-centered-on-mobile-view)
- [LOOM](https://www.loom.com/share/8f5ea143a2b24e8faae6d08d307ec14f)
=> OUT-727 Loader is not centered on Mobile View

prisma/migrations/20240815014449_remove_uq_for_label_deleted_at_for_tasks/migration.sql, prisma/schema.prisma, src/app/api/notification/notification.service.ts, src/app/api/tasks/tasks.service.ts, src/app/api/webhook/webhook.controller.ts, src/cmd/load-testing/deleteClients.ts
- [OUT-677 | In-product notification & Task do not disappear from client end when company is deleted/unassigned](https://linear.app/copilotplatforms/issue/OUT-677/in-product-notification-and-task-do-not-disappear-from-client-end-when)
=> OUT-677 | In-product notification & Task do not disappear from client end when company is deleted/unassigned

package.json, src/app/detail/ui/Sidebar.tsx, src/app/detail/ui/TaskEditor.tsx, src/cmd/load-testing/deleteClients.ts
- [LOOM](https://www.loom.com/share/827f8f2048fc4db1b13cae9e8e82901c?sid=bd3e29b8-8022-4ce1-85a8-0c35774c8d82) video shows the fast navigation from details page to the task board.
=> OUT-660 Loading spinner shows when going back to task list first time

src/app/api/tasks/tasks.service.ts, src/app/api/webhook/route.ts, src/app/api/webhook/webhook.controller.ts, src/app/api/webhook/webhook.service.ts, src/types/webhook.ts
- [OUT-742 | Handle notification side-effects when Client's company is updated](https://linear.app/copilotplatforms/issue/OUT-742/handle-notification-side-effects-when-clients-company-is-updated)
- Depends on https://github.com/copilot-platforms/tasks-app/pull/254
- While testing this, you need to change this webhook URL to point to the preview deployment TEMPORARILY. *Add this webhook to app config, and not workspace setting, since this can trigger multiple notifications to clients*
=> OUT-742 | Handle notification side-effects when Client's company is updated

src/app/detail/ui/TaskEditor.tsx
- [Dont let users break line for title in Details page (ref : Linear)](https://linear.app/copilotplatforms/issue/OUT-753/dont-let-users-break-line-for-title-in-details-page-ref-linear)
- [LOOM](https://www.loom.com/share/648fd74e76b8478db478690dfbe6a7cf)
=> OUT-753 Dont let users break line for title in Details page (ref : Linear)

src/app/detail/[task_id]/[user_type]/DetailStateUpdate.tsx, src/app/detail/[task_id]/[user_type]/page.tsx, src/app/page.tsx, src/utils/redirect.ts
- [OUT-766 | Opening task from notification center shows blank task details](https://linear.app/copilotplatforms/issue/OUT-766/opening-task-from-notification-center-shows-blank-task-details)
=> OUT-766 | Opening task from notification center shows blank task details

src/components/inputs/Selector.tsx
- [LOOM](https://www.loom.com/share/8db69e3ac61e43369567ef4bbc192b95?sid=ba909322-057b-4839-a20f-0b62eef38672)
=> OUT-769 Filter dropdown search input persists until I click somewhere on the page

src/components/inputs/ListComponent.tsx
- [Some weird arrows coming on autocomplete popper below the loading spinner on loading state](https://linear.app/copilotplatforms/issue/OUT-764/some-weird-arrows-coming-on-autocomplete-popper-below-the-loading)
=> OUT-764-hotfix

src/redux/features/taskBoardSlice.tsx
- [When selected assignee in Filter by drop-down is deleted, Board/List view shows blank until I click the tab](https://linear.app/copilotplatforms/issue/OUT-754/when-selected-assignee-in-filter-by-drop-down-is-deleted-boardlist)
- [LOOM](https://www.loom.com/share/f4a7650571f14ea7beb254d4b506f739)
=> OUT-754 When selected assignee in Filter by drop-down is deleted, Board/List view shows blank until I click the tab

src/components/inputs/ListComponent.tsx, src/components/inputs/Selector.tsx, src/theme/theme.ts, src/types/theme.d.ts
- [Some weird arrows coming on autocomplete popper below the loading spinner on loading state](https://linear.app/copilotplatforms/issue/OUT-764/some-weird-arrows-coming-on-autocomplete-popper-below-the-loading)
=> OUT-764, OUT-765-hotfix Some weird arrows coming on autocomplete popper below the loading spinner on loading state

src/app/page.tsx, src/app/ui/TaskBoard.tsx, src/components/layouts/EmptyState/DashboardEmptyState.tsx
[Screencast from 05-09-24 02:33:30 PM +0545.webm](https://github.com/user-attachments/assets/bf993f1e-43f8-4388-ac15-d50ebc077fb2)
=> Hotfix/out 800 "+ New Task" button shouldn't appear for clients if task board is empty

src/app/detail/ui/Sidebar.tsx, src/hooks/useWindowWidth.ts
- [LOOM](https://www.loom.com/share/f83e75c036a546fdbc15006df3370f8a)
=> OUT-808 Task details page opens Properties section by default in the mobile experience

src/app/api/core/utils/withErrorHandler.ts
- [OUT-752 | Improved Zod Error messages](https://linear.app/copilotplatforms/issue/OUT-752/improved-zod-error-messages)
=> OUT-752 | Clean Zod errors so we can debug in prod

src/hoc/DragDropHandler.tsx, src/redux/features/taskBoardSlice.tsx
=> OUT-817 Fix DnD - browser globe icon follows cursor when moving a task to a different status

src/app/api/users/users.service.ts, src/types/common.ts, src/utils/ordering.ts
- [OUT-823 | Clients should be shown in drop-down by creation date. Most recent ones first.](https://linear.app/copilotplatforms/issue/OUT-823/clients-should-be-shown-in-drop-down-by-creation-date-most-recent-ones)
=> OUT-823 | Clients should be shown in drop-down by creation date. Most recent ones first.

src/components/layouts/EmptyState/DashboardEmptyState.tsx
=> OUT-832 Incorrect content is shown in empty state on IU and CU end

package.json, src/app/api/core/utils/authenticate.ts, src/app/api/core/utils/withErrorHandler.ts, src/app/api/core/utils/withRetry.ts, src/types/CopilotApiError.ts, src/utils/CopilotAPI.ts, yarn.lock
- [OUT-836 | TypeError: fetch failed](https://linear.app/copilotplatforms/issue/OUT-836/typeerror-fetch-failed)
- [OUT-837 | TypeError: fetch failed](https://linear.app/copilotplatforms/issue/OUT-837)
- And other tasks in the past regarding rate-limits / 500 response from CopilotAPI
=> OUT-837 | OUT-836 | Add retry & delay mechanism to CopilotAPI

package.json, yarn.lock
- [Don't show resizing bars for images for Client users](https://linear.app/copilotplatforms/issue/OUT-850/dont-show-resizing-bars-for-images-for-client-users)
- [LOOM](https://www.loom.com/share/8e66874a83314051bd4f9b9f68cb306e)
=> OUT-850 Don't show resizing bars for images for Client users

package.json, yarn.lock
- [Image skeletons should have the same size as the image](https://linear.app/copilotplatforms/issue/OUT-858/image-skeletons-should-have-the-same-size-as-the-image)
- [LOOM](https://www.loom.com/share/b15711d005fb4da0bd2de454db07b9fe)
=> OUT-858 Image skeletons should have the same size as the image

src/app/api/tasks/tasks.service.ts
- [Product notification goes away from CU end when IU changes the company task status](https://linear.app/copilotplatforms/issue/OUT-797/product-notification-goes-away-from-cu-end-when-iu-changes-the-company)
=> OUT-797: Fix IU notification scenarios when moving tasks around

package.json, yarn.lock
- [Support drag&drop and pasting images into editor](https://linear.app/copilotplatforms/issue/OUT-825/support-draganddrop-and-pasting-images-into-editor)
- [Images are not fully left aligned.](https://linear.app/copilotplatforms/issue/OUT-877/images-are-not-fully-left-aligned)
=> OUT-825, OUT-877 Support drag&drop and pasting images into editor

package.json, src/hoc/ModifiedBackend.ts, yarn.lock
- [MaxWidth is not right on images on smaller screen when screen is changed from devtools. Image max width greater in task creation.](https://linear.app/copilotplatforms/issue/OUT-861/maxwidth-is-not-right-on-images-on-smaller-screen-when-screen-is)
- [COMMIT](https://github.com/aatbip/tapwrite/pull/12/commits/ef819e1214b12e2415a3650ad93e4718074cf117)
=> OUT-861 MaxWidth is not right on images on smaller screen when screen is changed from devtools. Image max width greater in task creation.

src/app/api/tasks/tasks.service.ts, src/app/detail/ui/Sidebar.tsx, src/app/ui/NewTaskForm.tsx, src/components/cards/ListViewTaskCard.tsx, src/components/inputs/Selector.tsx, src/components/layouts/FilterBar.tsx
- [OUT-821 | Opening "Filter by assignee" drop-down for econd time shows incorrect assignees](https://linear.app/copilotplatforms/issue/OUT-821/opening-filter-by-assignee-drop-down-for-second-time-shows-incorrect)
[Screencast from 2024-09-24 13-43-24.webm](https://github.com/user-attachments/assets/1f913fc1-6d17-4662-a6f4-6a366ea4ab2b)
=> OUT-821 | Opening "Filter by assignee" drop-down for second time shows incorrect assignees

src/app/api/tasks/tasks.service.ts, src/hoc/RealTime.tsx
- [OUT-890 | IU/Client can see the tasks that are assigned to another IU/client in real-time](https://linear.app/copilotplatforms/issue/OUT-890/iuclient-can-see-the-tasks-that-are-assigned-to-another-iuclient-in)
1. Client users aren't streamed tasks that belong to the workspace but are not assigned to them, so it is more secure.
2. There are a LOT less change events to listen and react to.
[Screencast from 2024-10-17 17-50-04.webm](https://github.com/user-attachments/assets/c9843358-a74f-4c9d-bd42-1cda6344c2d6)
=> OUT-890 | IU/Client can see the tasks that are assigned to another IU/client in real-time

src/app/api/tasks/tasks.service.ts
- [OUT-899 | IU should not receive in-product notifications when they complete the task assigned to companies](https://linear.app/copilotplatforms/issue/OUT-899/iu-should-not-receive-in-product-notifications-when-they-complete-the)
[Screencast from 2024-10-21 17-22-26.webm](https://github.com/user-attachments/assets/8d5bb8b9-2e11-45a8-a721-afe1159fed7d)
=> OUT-899 | IU should not receive in-product notifications when they complete the task assigned to companies

src/app/api/notification/notification.helpers.ts
- [OUT-914 | Add single quotes around taskName in comment email notification body](https://linear.app/copilotplatforms/issue/OUT-914/add-single-quotes-around-taskname-in-comment-email-notification-body)
=> OUT-914 | Add single quotes around taskName in comment email notification body

src/components/inputs/CommentInput.tsx
=> OUT 945 Text in comment input box wraps mid word without including a hyphen

src/app/api/tasks/[id]/client/route.ts, src/app/api/tasks/tasks.service.ts
[Screencast from 2024-10-23 17-37-26.webm](https://github.com/user-attachments/assets/1ae67d5b-c790-4380-a706-368fef24007d)
[Screencast from 2024-10-23 17-34-35.webm](https://github.com/user-attachments/assets/ee7ff441-bf0b-4247-8be2-245965a167e2)
[Screencast from 2024-10-23 17-30-58.webm](https://github.com/user-attachments/assets/7e0cfcc1-cd3f-49bc-adcf-e6e61798c780)
=> OUT-950 | OUT-923 | OUT-912 | OUT-911 | Notification Fixes for Tasks main

src/app/api/tasks/tasks.service.ts, src/app/api/webhook/webhook.controller.ts, src/app/api/webhook/webhook.service.ts, src/utils/CopilotAPI.ts
(refreshing to change notification chip count is not needed - it just seems to reflect a bit faster this way)
[Screencast from 2024-10-24 14-34-53.webm](https://github.com/user-attachments/assets/1d33d443-2a31-491a-a691-828d46ad1b37)
[Screencast from 2024-10-24 14-37-21.webm](https://github.com/user-attachments/assets/219d3d3d-c52d-48a0-8857-907b92964f71)
[Screencast from 2024-10-24 14-38-47.webm](https://github.com/user-attachments/assets/76d4dbb5-87d4-4e82-b54d-b65db7f01ff9)
[Uploading Screencast from 2024-10-24 14-40-01.webm…]()
=> OUT-908 | Delete task for CU and decrement notification badge when the assignee company is deleted

src/app/api/tasks/tasks.service.ts
Screencast:
[Screencast from 2024-10-28 20-28-17.webm](https://github.com/user-attachments/assets/aed036b9-04f9-4b1a-bc3a-62543989e58a)
=> OUT-949 | The initiator of the action shouldn't get a notification (if they are also the recipient)

src/app/api/tasks/tasks.service.ts
- I still have the code commented in case something like this needs to be reimplemented / there are requirement changes
=> OUT-974 | Task notification gets deleted when client assignee is deleted.

package.json, src/app/detail/ui/TaskEditor.tsx, src/components/AttachmentLayout.tsx, yarn.lock
- [Attachment button is missing on editor](https://linear.app/copilotplatforms/issue/OUT-990/attachment-button-is-missing-on-editor)
Tested on attachments and images.
=> OUT-990 Attachment button is missing on editor

src/app/detail/ui/ActivityLog.tsx, src/app/detail/ui/Comments.tsx, src/components/atoms/CopilotAvatar.tsx, src/components/inputs/CommentInput.tsx
=> OUT-976 | Match CU's profile image when writing a comment

src/components/AttachmentLayout.tsx
- [On mobile, selecting an attachment for the first time triggers the hover state](https://linear.app/copilotplatforms/issue/OUT-998/on-mobile-selecting-an-attachment-for-the-first-time-triggers-the)
- [On mobile, download icon should always be shown on attachment cards](https://linear.app/copilotplatforms/issue/OUT-999/on-mobile-download-icon-should-always-be-shown-on-attachment-cards)
- [LOOM](https://www.loom.com/share/be2bcbb1a3a646d19e250e30f05f2ad2)
=> OUT-998, OUT-999 On mobile, selecting an attachment for the first time triggers the hover state

package.json, yarn.lock
- [Images and attachments should not show a selected state for CUs](https://linear.app/copilotplatforms/issue/OUT-993/images-and-attachments-should-not-show-a-selected-state-for-cus)
- [Inconsistent focus states for images and attachments](https://linear.app/copilotplatforms/issue/OUT-996/inconsistent-focus-states-for-images-and-attachments)
- [LOOM](https://www.loom.com/share/a0cf9b798f6e4f00971ab49445b3cd7e)
=> OUT-996, OUT-993 Inconsistent focus states for images and attachments

src/app/detail/ui/TaskEditor.tsx, src/app/detail/ui/styledComponent.tsx, src/app/globals.css, src/components/AttachmentLayout.tsx
- [Remove white space between task description and activity feed](https://linear.app/copilotplatforms/issue/OUT-995/remove-white-space-between-task-description-and-activity-feed)
- [Update the right padding on Desktop for an attachment card from 8px to 12px](https://linear.app/copilotplatforms/issue/OUT-997/update-the-right-padding-on-desktop-for-an-attachment-card-from-8px-to)
- [LOOM](https://www.loom.com/share/ca32ff53e23b46d7ae243ac9885b5106)
=> OUT-995, OUT-997 Remove white space between task description and activity feed

package.json, src/app/detail/ui/TaskEditor.tsx, src/app/ui/NewTaskForm.tsx, src/components/AttachmentLayout.tsx, src/constants/attachments.ts, yarn.lock
- [LOOM](https://www.loom.com/share/448dd04a60624862aa5f719afb9eedc7)
=> OUT-1000 When using /upload or the upload button, the image files should show as attachment

src/components/cards/CommentCard.tsx, src/utils/getTimeDifference.ts
=> OUT-1006 | If a task was created <60 seconds ago it just say "Just now" where the created time iso

src/components/cards/CommentCard.tsx
[Screencast from 2024-11-12 18-09-45.webm](https://github.com/user-attachments/assets/11d847ac-ded5-4937-9412-86dbd0eb5ffb)
=> OUT-1002 | On mobile, kebab menu should always be shown on task comments

src/app/actions.ts, src/app/api/attachments/attachments.controller.ts, src/app/api/attachments/attachments.service.ts, src/app/api/tasks/tasks.service.ts, src/app/detail/[task_id]/[user_type]/page.tsx, src/app/detail/ui/TaskEditor.tsx, src/app/page.tsx, src/app/ui/Modal_NewTaskForm.tsx, src/app/ui/NewTaskForm.tsx, src/constants/attachments.ts, src/types/constants.ts, src/utils/SupabaseActions.ts, src/utils/inlineImage.ts, src/utils/signedUrlReplacer.ts
=> OUT-972 | Set up proper Supabase Storage folder structure in SupabaseService

src/app/detail/ui/TaskEditor.tsx, src/components/inputs/CommentInput.tsx, src/hoc/RealTime.tsx
- When the value of the `body` attribute was larger than Postgres replica's pagesize, Supabase Realtime omitted this field. Our Realtime handler picked this up and set `body` to `undefined`, which was causing the task descriptions to disappear
- Ref 1: https://github.com/supabase/realtime/issues/223
- Ref 2: https://www.postgresql.org/docs/current/storage-toast.html
[Screencast from 2024-11-14 19-28-32.webm](https://github.com/user-attachments/assets/2453b7fa-08b8-4c09-bf89-e1e3834aae7e)
[Screencast from 2024-11-14 19-26-41.webm](https://github.com/user-attachments/assets/94890067-6a56-4fee-b9f2-e9a5b0f42eed)
=> OUT-1026 | Task description is temporarily disappearing after leaving a comment on a task with multiple attachments and images

prisma/migrations/20241116013134_feat_add_is_archived_and_last_archived_date_fields_to_tasks/migration.sql, prisma/schema/task.prisma, src/app/api/tasks/tasks.service.ts, src/cmd/load-testing/load-testing.service.ts, src/types/dto/tasks.dto.ts
=> OUT-1016 | Implement isArchived & lastArchivedDate fields for Tasks API

src/app/ui/NewTaskForm.tsx
=> OUT-1035 | Fix spacing between Description field label and its text field

src/components/inputs/DisplaySelector.tsx
=> OUT-1050 | Add and retain selected design state to List/Board view buttons in Display drawer

src/app/page.tsx, src/utils/redirect.ts
=> OUT-1056 | Opening task from Task assigned email shows incorrect task details

src/app/detail/[task_id]/[user_type]/page.tsx, src/app/detail/ui/LastArchiveField.tsx, src/components/buttons/ArchiveBtn.tsx, src/components/cards/ListViewTaskCard.tsx
[Screencast from 2024-11-21 18-37-16.webm](https://github.com/user-attachments/assets/0758ed29-e54b-48a6-b24a-7d17fa3d60ae)
=> OUT-1047 | OUT-1048 | OUT-1049 | OUT-1055 | Fix initial design & functionality issues

src/app/detail/ui/ArchiveWrapper.tsx, src/app/detail/ui/Sidebar.tsx, src/app/detail/ui/TaskEditor.tsx, src/hoc/ClientSideStateUpdate.tsx, src/hoc/RealTime.tsx, src/redux/features/taskBoardSlice.tsx
- [LOOM](https://www.loom.com/share/ff4b79e9b7a24ddf8baedc474e9f0d35)
=> OUT-1063 Archive indicator and properties tab breaks when one of the display toggles are disabled

package.json, yarn.lock
=> OUT-1027  | Hover state over attachments button should be a rectangle, not a circle

src/components/cards/CardDragLayer.tsx
=> OUT-1051 | Include archive icon when dragging & dropping a task in list view

src/components/cards/TaskCard.tsx
- Hover on the task card and notice the hover state background color is now `#F8F9FB` i.e. `gray[100]` according to the `theme.ts` design system
=> OUT 1064 Update hover state for a task

src/app/api/tasks/tasks.service.ts, src/app/ui/TaskBoard.tsx, src/components/cards/ListViewTaskCard.tsx, src/lib/db.ts, src/redux/features/taskBoardSlice.tsx, src/utils/sortTask.ts
```sql
ORDER by "tasks"."dueDate" asc nulls last, "tasks"."createdAt" DESC
```
[Screencast from 2024-11-27 15-21-43.webm](https://github.com/user-attachments/assets/a12a04ca-b2d9-4678-90ef-2c5d3f48e362)
=> OUT-1071 | Tasks should sort by due date, not created date

src/components/layouts/EmptyState/NoFilteredTasksState.tsx
- Unselect both the filters in the "Display" pop up then observe the vertical scroll doesn't appear during "No tasks found" screen
=> OUT 1089 Unnecessary scrollbar appears with 'No tasks found' empty state

src/app/detail/[task_id]/[user_type]/page.tsx, src/components/buttons/ArchiveBtn.tsx, src/components/buttons/SecondaryBtn.tsx, src/components/inputs/DisplaySelector.tsx, src/components/layouts/FilterBar.tsx
- [LOOM](https://www.loom.com/share/c6028bd5c77b4c329a02d3cc985ee484)
=> OUT-1097, OUT-1096 | Fix 'Display' button alignment issue

src/components/inputs/Selector.tsx, src/components/layouts/FilterBar.tsx, src/utils/noAssignee.ts
- [LOOM](https://www.loom.com/share/a4991955e780401fb3ee8d599535d8db)
=> OUT-773 | Show 'No matches found for {search-text}' when there is no search result

src/components/inputs/Selector.tsx
=> OUT-773 (hotfix) : Show 'No matches found for {search-text}' when there is no search result

src/app/detail/[task_id]/[user_type]/DetailStateUpdate.tsx, src/app/detail/ui/Sidebar.tsx
- [LOOM](https://www.loom.com/share/05a34b3c18bd46bb8a40c2ec79d37bb6)
=> OUT-1108 | Task details are missing when opening a task from email notification & notification center

src/components/inputs/Selector.tsx
=> OUT-1109 | Design regression from m5 on assignee selector

src/components/cards/ClientTaskCard.tsx, src/components/cards/ListViewTaskCard.tsx, src/components/cards/TaskCard.tsx, src/components/layouts/DueDateLayout.tsx, src/utils/isTaskCompleted.ts
- [LOOM](https://www.loom.com/share/d1a7ccfa82374f8680a29698649ff0e8)
=> OUT-1101 | Change past due date from red to standard grey when status = done

src/app/manage-templates/ui/TemplateForm.tsx
=> OUT-1113 | template title cannot be empty

src/app/ui/MenuBoxContainer.tsx, src/app/ui/NewTaskForm.tsx
- [LOOM](https://www.loom.com/share/a8c4b4f9adde4629b5fecaa743af6b15)
=> OUT-1126, OUT-1124 | Status doesn’t update correctly when template is applied

src/app/manage-templates/page.tsx, src/app/manage-templates/ui/Header.tsx
[Screencast from 2024-12-10 15-17-29.webm](https://github.com/user-attachments/assets/191cb707-eb3d-4340-9d37-f9bb37132027)
=> OUT-1122 | OUT-1125 | '+ Create template' button doesn't appear / disappear in real-time

src/components/inputs/Selector.tsx
[Screencast from 2024-12-10 15-31-27.webm](https://github.com/user-attachments/assets/c555cec8-5eb4-4245-b94a-c9a5b31c172d)
=> OUT-1116 | Applying the same template a second time causes part of the templates menu to disappear

src/components/cards/TemplateCard.tsx
[Screencast from 2024-12-10 18-04-35.webm](https://github.com/user-attachments/assets/046e8a95-232a-45c7-967f-3e15a96fe4a3)
=> OUT-1119 | Template cards in manage templates should be clickable

src/app/detail/[task_id]/[user_type]/page.tsx, src/app/detail/ui/Sidebar.tsx, src/app/manage-templates/page.tsx, src/app/manage-templates/ui/Header.tsx, src/app/manage-templates/ui/TemplateForm.tsx, src/app/ui/NewTaskForm.tsx
- [LOOM](https://www.loom.com/share/d76b6515410245e8ac3f57c8f0c3d176)
=> OUT-1141, OUT-1144, OUT-1146, OUT-1140, OUT-1150 | Vertical line in the Manage templates page does not extend all the way

src/app/detail/ui/MenuBoxContainer.tsx, src/app/ui/NewTaskForm.tsx, src/components/buttons/ArchiveBtn.tsx, src/redux/features/templateSlice.tsx
- [LOOM](https://www.loom.com/share/6c1437341a7e4fbab9ccb83f075666c0)
=> OUT-1147, OUT-1149, OUT-1133 | Ellipsis hover state is always showing on task details page

prisma/migrations/20241211122347_add_unique_constraint_to_task_templates_title_and_workspace_id/migration.sql, prisma/schema/taskTemplate.prisma, src/app/api/tasks/templates/templates.service.ts, src/app/manage-templates/ui/TemplateBoard.tsx, src/utils/sql.ts
```sql
-- Identify dup titles
SELECT "TaskTemplates"."title", "TaskTemplates"."workspaceId", count(*)
FROM "TaskTemplates"
GROUP BY "TaskTemplates"."title", "TaskTemplates"."workspaceId"
HAVING COUNT(*) > 1;
```
```sql
-- Delete dup template having higher row number (deletes everything except the original template for a title)
WITH ranked_templates AS (
SELECT id, title, "workspaceId",
ROW_NUMBER() OVER (
PARTITION BY title, "workspaceId"
ORDER BY id ASC
) AS row_num
FROM "TaskTemplates"
)
DELETE FROM "TaskTemplates"
WHERE id IN (
SELECT id
FROM ranked_templates
WHERE row_num > 1
);
```
1st creation:
2nd creation:
3rd creation:
UI view:
=> OUT-1117 | Do not allow templates with duplicate names

package.json, yarn.lock
=> OUT-1039 | SecurityError: LockManager.request: request() is not allowed in this context

src/components/layouts/EmptyState/DashboardEmptyState.tsx, src/components/layouts/Header.tsx
=> OUT-1155 | Rename button label to ´+ Create task´.

src/app/client/page.tsx, src/app/ui/TaskBoard.tsx, src/components/cards/TaskColumn.tsx, src/components/layouts/EmptyState/DashboardEmptyState.tsx, src/hoc/ClientSideStateUpdate.tsx, src/redux/features/taskBoardSlice.tsx, src/types/common.ts, src/utils/previewMode.ts
=> OUT-1161 | OUT-1162 | Add support for Preview mode in client & company details view

src/app/ui/Modal_NewTaskForm.tsx, src/app/ui/NewTaskForm.tsx
- [LOOM](https://www.loom.com/share/93037ecd385c4a16b41e8645839b72bb)
=> OUT-1154, OUT-1167 | Task creation modal doesn't persist with applied template details

src/app/detail/ui/ActivityWrapper.tsx, src/app/ui/Modal_NewTaskForm.tsx, src/app/ui/NewTaskForm.tsx, src/components/inputs/Autocomplete.tsx, src/components/inputs/CommentInput.tsx, src/components/inputs/ListComponent.tsx, src/components/inputs/Selector.tsx, src/components/inputs/TextField.tsx
=> OUT-1156, OUT-1168 | Design changes on current selector component

src/app/ui/TaskBoard.tsx
- [LOOM](https://www.loom.com/share/d9273f28e1264892a4a6575f2c8f2e2e)
=> OUT-1169 | Improve loading experience of tasks empty state

src/app/ui/TaskBoard.tsx
- [LOOM](https://www.loom.com/share/78d4f077391c45418e41ee072237827f)
=> OUT-1176 | Switching between views shows blank screen momentarily

src/app/manage-templates/ui/Header.tsx, src/components/layouts/Header.tsx, src/components/layouts/HeaderBreadcrumbs.tsx
[Screencast from 2024-12-26 12-43-54.webm](https://github.com/user-attachments/assets/a83591cd-70f5-4946-8565-10bc8bb140da)
=> OUT-1202 | Filters and selector reappearing

src/components/cards/CommentCard.tsx
=> OUT-1180 | Hover state is not centered around the kebab menu in comments

src/app/detail/[task_id]/[user_type]/page.tsx
=> (HOTFIX) | feature/m7

src/app/detail/[task_id]/[user_type]/page.tsx
- [Delete option missing for IU](https://linear.app/copilotplatforms/issue/OUT-1206/delete-option-missing-for-tasks-on-iu-end)
Show the menu on task details when we see the user type is internal OR we are in preview mode (client/company details).
previously the logic we had was  
```
params.user_type === UserType.INTERNAL_USER || (!!getPreviewMode(tokenPayload) && <MenuBoxContainer />)
```
In the above is the user type is true, the `||` does not get executed and we render nothing. This is why the menu was not shown.
- skipped, this is an attempt to follow up quickly on a bug found and I haven't setup my env fully for e2e testing.
=> fix: show menu on IU task details

prisma/migrations/20241227091629_add_due_date_changed_enum_prop_for_activity_log/migration.sql, prisma/schema/activityLog.prisma, src/app/api/activity-logs/const.ts, src/app/api/activity-logs/schemas/DueDateChangedSchema.ts, src/app/api/tasks/tasks.logger.ts, src/app/detail/ui/ActivityLog.tsx, src/components/layouts/DueDateLayout.tsx, src/utils/dueDateFormatter.ts
=> OUT-1191, OUT-1192, OUT-1193 | Add support for DueDate in Activity Logs

src/app/api/activity-logs/services/activity-log.service.ts
Edit: ignore the "2" "2" for fallbacks
=> OUT-1220 | Add ordering to Activity Logs so that creation events are sorted in order

src/app/api/tasks/tasks.logger.ts
- [LOOM](https://www.loom.com/share/bfe98686b23c46a2a562b0babf5c7778?focus_title=1&muted=1&from_recorder=1)
=> OUT-1216 | Activity feed updates sometimes take ~30 sec to show

src/app/detail/[task_id]/[user_type]/actions.ts, src/app/detail/ui/ActivityLog.tsx, src/app/detail/ui/ActivityWrapper.tsx, src/app/detail/ui/Comments.tsx
- [LOOM](https://www.loom.com/share/d112b003f1c1421db92a4c4d3ea59367)
=> OUT-1219, OUT-1225 | Double animations on comments.

src/app/api/tasks/tasks.logger.ts, src/cmd/fill-activity-logs/fillTaskAssigned.ts
=> OUT-1226 | Revert automatic Task Assigned activity log on tasks

prisma/migrations/20250106090303_add_deleted_at_to_composite_unique_key_in_task_templates/migration.sql, prisma/schema/taskTemplate.prisma
=> OUT-1231 | Can not create template with the same name as the deleted template.

src/components/inputs/TextField.tsx
=> OUT-1230 | Prevent passing unrecognized props to the DOM from custom components

src/app/detail/ui/ActivityWrapper.tsx
- [LOOM](https://www.loom.com/share/9d5ae4e774324e158496eb22e0ac4dff)
=> OUT-1244 | Activity feed not updating for archived tasks after status change

src/app/ui/TaskBoard.tsx, src/components/cards/TaskRow.tsx
=> OUT-1245 | Create task button is missing in list view on client details page

.github/PULL_REQUEST_TEMPLATE.md
=> Qol: Remove task link from pr template

src/app/manage-templates/ui/TemplateForm.tsx
=> OUT-1247 | Fix template pop up heading alignment

src/app/api/notification/validate-count/validateCount.service.ts, src/cmd/fill-activity-logs/index.ts, src/types/client-notifications.ts
[Screencast from 2025-01-07 19-15-04.webm](https://github.com/user-attachments/assets/f11ac89c-aba1-482c-a059-04f787ac92d8)
=> OUT-1238 | Make validate-count robust by removing duplicate notifications for a single task

src/app/ui/TaskBoard.tsx, src/components/layouts/EmptyState/DashboardEmptyState.tsx
- We can see in the image that although we have the text : "_You don't have any tasks yet Tasks will show here once they’ve been assigned to you._", I've added create task button too, which should be in client view but it is a functionality for CRM's tasks app.
=> OUT-1246 | Incorrect empty state is shown for tasks on client details page

src/app/page.tsx, src/app/ui/TaskBoard.tsx, src/app/ui/TaskBoardAppBridge.tsx, src/hooks/app-bridge/types.ts, src/hooks/app-bridge/useActionsMenu.tsx, src/hooks/app-bridge/useBreadcrumbs.tsx, src/hooks/app-bridge/usePrimaryCta.tsx, src/hooks/app-bridge/useSecondaryCta.tsx, src/types/common.ts, src/utils/https.ts
[Screencast from 2025-01-10 15-20-13.webm](https://github.com/user-attachments/assets/3c67504d-1788-4ccc-932d-cca1635d2224)
Design is not up to us - it is implemented from the copilot side.
=> OUT-1254 | OUT-1255 | Implement "Create task" button & "Manage templates" menu option for Tasks Board

src/app/detail/[task_id]/[user_type]/page.tsx, src/app/detail/ui/MenuBoxContainer.tsx, src/app/detail/ui/ToggleButtonContainer.tsx, src/components/layouts/HeaderBreadcrumbs.tsx
[Screencast from 2025-01-13 17-19-45.webm](https://github.com/user-attachments/assets/d698416f-6265-4c7b-9a1e-90999fb352b4)
=> OUT-1263 | Implement Breadcrumbs for Task Details Page

src/app/detail/[task_id]/[user_type]/page.tsx, src/app/detail/ui/ArchiveWrapper.tsx, src/app/detail/ui/DetailAppBridge.tsx, src/app/detail/ui/MenuBoxContainer.tsx, src/app/detail/ui/ToggleButtonContainer.tsx, src/app/ui/TaskBoardAppBridge.tsx, src/components/layouts/HeaderBreadcrumbs.tsx
[Screencast from 2025-01-13 17-50-11.webm](https://github.com/user-attachments/assets/42c82bef-eb9e-49c0-8f04-433ff9beb17d)
=> OUT-1259 | Implement CTA buttons for Task Details Page

src/app/detail/[task_id]/[user_type]/page.tsx, src/app/detail/ui/Sidebar.tsx, src/app/detail/ui/ToggleButtonContainer.tsx, src/components/buttons/ToggleBtn.tsx
[Screencast from 2025-01-14 15-34-02.webm](https://github.com/user-attachments/assets/fc7924a8-f10c-4f15-956d-36531fb43807)
=> OUT-1265 | Task details page should match designs, empty header

src/app/detail/[task_id]/[user_type]/page.tsx, src/hooks/app-bridge/useSecondaryCta.tsx
=> OUT-1276 | OUT-1278 | Wrong header elements showing on task details page + Fix secondary CTA icon

src/app/manage-templates/ui/ManageTemplatesAppBridge.tsx, src/app/ui/TaskBoardAppBridge.tsx
=> OUT-1273, OUT-1274 | Incorrect icon is shown for 'Manage templates' option, Breadcrumbs 'Manage templates' is clickable

src/app/client/page.tsx, src/app/detail/[task_id]/[user_type]/page.tsx, src/app/ui/TaskBoardAppBridge.tsx, src/components/layouts/HeaderBreadcrumbs.tsx
- [LOOM](https://www.loom.com/share/83314d3ad2ba456d97a1803fe03a8c3a)
=> OUT-1275 | Breadcrumbs are not shown for task details page on client side

src/app/detail/ui/DetailAppBridge.tsx, src/app/manage-templates/ui/TemplateForm.tsx, src/hooks/app-bridge/types.ts, src/hooks/app-bridge/useActionsMenu.tsx
=> OUT-1282 | Delete action menu item text is not red

src/app/_fetchers/TaskDataFetcher.tsx, src/app/ui/TaskBoard.tsx, src/components/layouts/FilterBar.tsx
- [LOOM](https://www.loom.com/share/1a708936fba24253bfeb481d0729b11c)
=> OUT-1272 | No filtered task screen showing on tasks app for a split second on first load.

src/app/page.tsx, src/app/ui/TaskBoard.tsx, src/app/ui/TaskBoardAppBridge.tsx
=> OUT-1299 | Remove '+ Create task' button from header for empty state

src/app/detail/ui/Sidebar.tsx, src/components/inputs/Selector.tsx, src/types/interfaces.ts
=> OUT-1307 | Show the previously selected assignee at the top of the Assignee Selector

src/app/detail/ui/Sidebar.tsx, src/components/layouts/ConfirmDeleteUI.tsx, src/components/layouts/ConfirmUI.tsx, src/redux/features/taskDetailsSlice.ts
- [LOOM](https://www.loom.com/share/fa98551f3be848429d12f982970fd87f). Tested on mobile view too.
=> OUT-1309 | Implement Confirmation Modal UI

src/app/detail/ui/Sidebar.tsx, src/components/inputs/Selector.tsx
=> OUT-1318 | Reassignment selector on sidebar issues

src/app/api/notification/notification.service.ts, src/app/api/tasks/task-notifications.service.ts
[Screencast from 2025-01-27 15-21-44.webm](https://github.com/user-attachments/assets/8c96e3b2-7fca-426e-81fe-2c731cfa9476)
=> OUT-1324 | Fix IU Notifications not getting removed for incomplete tasks

src/components/inputs/Selector.tsx
- [LOOM](https://www.loom.com/share/1db382973b224d1aa39ed1d8ab3fcf72)
=> OUT-1321 | Reassignment modal should close after click on assignees name

src/app/api/activity-logs/const.ts, src/app/api/activity-logs/services/activity-log.service.ts, src/app/api/core/utils/withErrorHandler.ts, src/app/api/tasks/tasks.service.ts, src/hoc/RealTime.tsx, src/utils/shouldConfirmBeforeReassign.ts
- [LOOM](https://www.loom.com/share/6abd22d21f074164ae4ff9d4ea8413b2)
=> OUT-1311, OUT-1326, OUT-1327 | Hide all activity logs before reassignment if task reassigned to access limited IU

src/app/detail/ui/Sidebar.tsx, src/hoc/RealTime.tsx
=> OUT-1328 | Images are not loading in task description, disappearing after upload

src/app/api/activity-logs/services/activity-log.service.ts, src/app/api/tasks/tasks.service.ts, src/app/api/users/users.service.ts, src/app/api/webhook/webhook.service.ts, src/cmd/load-testing/deleteClients.ts, src/constants/users.ts
=> OUT-1333 | Total list of tasks is not being rendered for Client Access Limited IU

src/app/detail/ui/Sidebar.tsx, src/components/layouts/ConfirmUI.tsx
=> OUT-1342 | Bold names in confirmation modal

src/components/inputs/Selector.tsx
- [LOOM](https://www.loom.com/share/aa00b8722f4d4fc3a380937ab5924875)
=> OUT-1339 | Selected assignee is not shown at the top of the Assignee Selector on page refresh

src/components/inputs/Selector.tsx
=> OUT-1341 | OUT-1320 | Fix design issues with Assignee Selector

src/components/inputs/DatePickerComponent.tsx, src/components/inputs/DisplaySelector.tsx, src/components/inputs/Selector-WorkflowState.tsx, src/components/inputs/Selector.tsx, src/theme/theme.ts
- [LOOM](https://www.loom.com/share/89cff42d34e8472cb25b56acd93af7b5)
=> OUT-1322 | Text on task properties should not be selectable

package.json, src/app/page.tsx, src/config/index.ts, src/hoc/RealTime.tsx, src/utils/redirect.ts, yarn.lock
[Screencast from 2025-02-05 17-36-35.webm](https://github.com/user-attachments/assets/fa3ff985-3dd1-4cb2-97e3-e8dfc209d852)
[Screencast from 2025-02-05 17-38-06.webm](https://github.com/user-attachments/assets/13d395ce-632f-468d-bf3f-8aa7312573df)
=> OUT-1303 | Fix VERCEL_URL navigation logic

src/app/api/notification/notification.service.ts, src/app/api/tasks/tasks.service.ts, src/jobs/notifications/index.ts, src/jobs/notifications/send-task-create-notifications.ts, src/jobs/notifications/send-task-update-notifications.ts
=> OUT-1352 | Implement task queue for notifications on task update

src/app/detail/ui/TaskEditor.tsx
=> OUT-1377 | Task description dissapearing when opening tasks.

src/app/api/notification/notification.service.ts
[Screencast from 2025-02-10 16-59-58.webm](https://github.com/user-attachments/assets/b09f3c2d-6ad9-4754-acf1-2f035be75191)
=> OUT-1390 | Fix Unique Constraint issue in InternalUserNotifications table while deleting notifications

src/components/AttachmentLayout.tsx, src/components/cards/CommentCard.tsx, src/components/inputs/CommentInput.tsx
=> OUT-1381 | Enable attachments and images in comments

.github/workflows/trigger.yml, package.json, src/app/api/activity-logs/services/activity-log.service.ts, src/components/cards/CommentCard.tsx, src/components/inputs/CommentInput.tsx, src/theme/theme.ts, src/types/theme.d.ts, yarn.lock
- [LOOM](https://www.loom.com/share/d990af0b4d97425aaa8303e1e4c4b013)
=> OUT-1380 | Comment box designs

src/components/cards/CommentCard.tsx
No access on hover in the bottom image.
=> OUT-1412 | Users should only be able to edit their own comments

src/components/buttonsGroup/EditCommentButtons.tsx, src/components/cards/CommentCard.tsx, src/components/inputs/CommentInput.tsx
- [LOOM](https://www.loom.com/share/54cd0f74b5d0410eb99445d3caed0627)
=> OUT-1426 | Comment box area has inconsistent width

src/components/inputs/CommentInput.tsx
=> OUT-1424 | Remove console log for 'Comment cannot be empty'

package.json, yarn.lock
- [LOOM](https://www.loom.com/share/03aa1495eeef4ed29f376fc65c8d38a3)
=> OUT-1421 | Add Image option to / menu

src/app/detail/ui/ImagePreviewModal/ImagePreviewHeader.tsx, src/app/detail/ui/ImagePreviewModal/ImageRenderer.tsx, src/components/atoms/Tooltip.tsx
=> OUT-1420 | Add tooltips to image preview buttons on hover

src/components/inputs/MenuBox.tsx
=> OUT-1441 | Add border radius to toggle menu

src/app/detail/ui/ActivityLog.tsx, src/app/detail/ui/styledComponent.tsx
=> OUT-1429 | Split first and last name in activity feed to avoid new lines

src/components/cards/TemplateCard.tsx, src/components/inputs/MenuBox.tsx
[Screencast from 2025-02-24 18-30-12.webm](https://github.com/user-attachments/assets/f04d8e23-abde-40ba-8431-e14947c41207)
=> OUT-1452 | Match fade in/out transition for kebab menu

src/utils/sortTask.ts
- [LOOM](https://www.loom.com/share/50bb5072308940eba8a7282e275f0800?focus_title=1&muted=1&from_recorder=1)
=> OUT-1467 | Tasks reposition on hover in board view

src/app/api/activity-logs/services/activity-log.service.ts, src/app/api/comment/comment.controller.ts, src/app/api/comment/comment.service.ts
- `/api/activity-logs` GET endpoint - intentional and only in scope of this milestone
- `/api/comments` GET endpoint - intentional and only in scope of this milestone
=> OUT-1497 | API - Add initiator details to replies & Order replies by earliest first

src/app/api/activity-logs/services/activity-log.service.ts, src/app/api/comment/comment.controller.ts, src/utils/signedUrlReplacer.ts
- GET `/api/activity-logs/:id` -> comments + comment replies (Loading of signed media like images and attachments)
- GET `/api/comments` -> Loading of signed media like images and attachments for a `parentId`
=> OUT-1499 | Add support for media & attachments in GET Replies API

package.json, prisma/migrations/20250306131831_add_deleted_at_to_activity_logs/migration.sql, prisma/schema/activityLog.prisma, src/app/api/activity-logs/services/activity-log.service.ts, src/app/api/comment/comment.service.ts, src/types/dto/comment.dto.ts, yarn.lock
https://github.com/user-attachments/assets/bc5f16a5-9c88-4f5f-b7e5-d0a9f6b14002
- Added `nodemon` package to run next server in debug mode with hot reloading
- GET `/api/activity-logs` -> Activity logs can now house deleted comments
=> OUT-1463 | Support deleted parent comment when comment has replies

src/app/detail/ui/ActivityWrapper.tsx, src/app/detail/ui/Comments.tsx, src/components/cards/CommentCard.tsx, src/components/cards/ReplyCard.tsx, src/components/inputs/ReplyInput.tsx, src/components/layouts/ConfirmDeleteUI.tsx, src/utils/checkOptimisticStableId.ts
- [LOOM](https://www.loom.com/share/b8695656c4284949a9fa379c7b0c2eaf?focus_title=1&muted=1&from_recorder=1)
- general comment/activity-log functionality because replies share all the endpoints and functions related to comment/activity-logs.
=> OUT-1487 | Add support for optimistic update and animations for replies while creating/deleting

src/jobs/notifications/send-reply-create-notifications.ts
- `send-reply-create-notifications` -> IU header text and Client email CTA button text
=> OUT-1515 | OUT-1516: Improvements to Notification copy

src/components/cards/CommentCard.tsx, src/components/cards/ReplyCard.tsx, src/components/inputs/ReplyInput.tsx
- [LOOM](https://www.loom.com/share/01458341a7f541c7b926b8b4a0aa6219)- OUT-1523
- [LOOM](https://www.loom.com/share/23b50bd4af3d48939a3e43356a9fdbac) - OUT-1529
- [LOOM](https://www.loom.com/share/bac6907b54df444c808724cef37f7c55) - OUT-1512
=> OUT-1523, OUT-1529, OUT-1512 | Comment edits do not display in real time

src/app/detail/ui/ImagePreviewModal/index.tsx, src/components/inputs/ReplyInput.tsx
- [LOOM, OUT-1532](https://www.loom.com/share/10ad02641d1c44bba243dfa36dd65df6)
=> OUT-1533, OUT-1532 | Contents of reply submission box are not vertically centered

package.json, src/utils/generateRandomString.ts, src/utils/signedTemplateUrlReplacer.ts, yarn.lock
https://github.com/user-attachments/assets/46d246cd-2d50-4150-9641-737ff3730a7d
=> OUT-1530 | TypeError: crypto.randomUUID is not a function

src/components/atoms/OverlappingAvatars.tsx, src/components/cards/CollapsibleReplyCard.tsx
=> OUT-1539 | Overlapping avatars containing deleted users is messed up

package.json
Ref: https://github.com/supabase/supabase-js/issues/936#issuecomment-2691252604
https://github.com/user-attachments/assets/6f40cb0b-220a-4970-80d9-e99f5a3d138a
- Realtime behavior
=> OUT-1465 | SecurityError: LockManager.request: request() is not allowed in this context

src/app/detail/ui/styledComponent.tsx, src/components/cards/CollapsibleReplyCard.tsx, src/components/cards/CommentCard.tsx, src/components/cards/DeletedCommentCard.tsx, src/components/cards/ReplyCard.tsx, src/components/inputs/CommentInput.tsx, src/components/inputs/ReplyInput.tsx
[Screencast from 03-17-2025 03:17:28 PM.webm](https://github.com/user-attachments/assets/9e77e162-e723-44b8-ad32-27af2c6c42ad)
- Comment reply designs in a comment card.
=> OUT-1522 | Add droppable area indicator when user drags file to a reply

prisma/migrations/20250327094204_add_subtask_count_to_tasks/migration.sql, prisma/schema/task.prisma, src/app/api/core/services/base.service.ts, src/app/api/tasks/subtasks.service.ts, src/app/api/tasks/tasks.service.ts, src/cmd/load-testing/load-testing.service.ts
https://github.com/user-attachments/assets/495c3eca-e2a3-44ea-86a0-5977e554949e
https://github.com/user-attachments/assets/ce303aaa-d740-4771-a102-e2083e9f9bc9
- CRUD endpoints for `/api/tasks`
=> OUT-1554 | Add `subtaskCounts` tracking column for Realtime support

src/app/detail/ui/NewTaskCard.tsx, src/app/detail/ui/Subtasks.tsx, src/utils/optimisticCommentUtils.ts, src/utils/optimisticTaskUtils.ts
- [LOOM](https://www.loom.com/share/d89073c84a254c0287755ea939a11b5e)
- Sub tasks component.
=> OUT-1581 | Optimistically update UI for sub task creation

src/components/inputs/ReplyInput.tsx
- [LOOM](https://www.loom.com/share/ba46fc675e48473f9c29ca7e1afeb619)
=> OUT-1600 | Text editor doesn't work for reply comment

src/components/atoms/TaskMetaItems.tsx
Previously this used to falsely show "0"
=> OUT-1620 | Bug: Tasks with inaccessible subtasks appear in card should not show '0' as subtask count

src/app/api/tasks/[id]/path/route.ts, src/app/api/tasks/subtasks.service.ts, src/app/api/tasks/tasks.controller.ts, src/app/api/tasks/tasks.service.ts, src/app/detail/[task_id]/[user_type]/page.tsx, src/app/manage-templates/ui/Header.tsx, src/components/layouts/HeaderBreadcrumbs.tsx, src/types/db.ts, src/types/dto/tasks.dto.ts, src/utils/ltree.ts
=> OUT-1597 | Show all ancestor task titles in App Bridge header

src/app/detail/ui/TaskCardList.tsx, src/components/cards/TaskCard.tsx, src/redux/features/taskBoardSlice.tsx
- [LOOM](https://www.loom.com/share/dcf51e4080e340f0ae62cb68b3ac44d5)
=> OUT-1618 | Board view flickers with loading skeletons when switching from list view

src/app/detail/ui/Subtasks.tsx, src/app/detail/ui/TaskCardList.tsx
=> OUT-1624 | Assignee copilot avatar returns to previous one while changing in sub task list

src/components/layouts/HeaderBreadcrumbs.tsx
=> OUT-1621 | Disable clickability and hover state for the last task breadcrumb on the task details page

src/hoc/RealTime.tsx, src/lib/realtime.ts
https://github.com/user-attachments/assets/8aef2c11-78dd-4ff9-b44e-735c9ae3dbd1
=> OUT-1638 | Page does not reroute to parent task page when subtask deleted

src/app/detail/[task_id]/[user_type]/actions.ts, src/app/detail/ui/TaskEditor.tsx
- [LOOM](https://www.loom.com/share/6b979f4bf40044c5b2f8598c5be78871)
=> OUT-1626 | Realtime issue on navigation from parent to child task.

src/app/detail/ui/Sidebar.tsx
- [LOOM](https://www.loom.com/share/b59ccd00bb46405eaa4b9f21d6f50c7d)
- Was only able to reproduce this issue on smaller resolution. Please test accordingly.
=> OUT-1647 | Task details page content shifts slightly left when fully loaded

src/app/detail/ui/NewTaskCard.tsx, src/app/ui/NewTaskForm.tsx, src/components/AttachmentLayout.tsx, src/components/inputs/DatePickerComponent.tsx, src/components/inputs/Selector-WorkflowState.tsx, src/components/inputs/Selector.tsx
- [LOOM](https://www.loom.com/share/a0975beea1834ddf806d9f32a746c4b7)
=> OUT-1635, OUT-1634, OUT-1582 | Change copy for empty due date property

src/app/detail/ui/NewTaskCard.tsx
- [LOOM](https://www.loom.com/share/ca5c2e2c3d914205976914b2c23aaccc)
=> OUT-1661 | Hide create subtask form after subtask is created

src/app/detail/ui/ActivityWrapper.tsx, src/app/detail/ui/TaskCardList.tsx, src/app/detail/ui/styledComponent.tsx
=> OUT-1662, OUT-1663 | Activity feed vertical line sticks out of top profile icon

src/app/api/tasks/tasks.service.ts
=> OUT-1669 | When trying to open Tasks app as staff user, it shows 'Something went wrong' error

src/app/_fetchers/AssigneeFetcher.tsx, src/app/api/users/users.controller.ts, src/app/api/users/users.service.ts, src/app/detail/[task_id]/[user_type]/page.tsx, src/app/detail/ui/NewTaskCard.tsx, src/app/detail/ui/TaskCardList.tsx, src/hoc/ClientSideStateUpdate.tsx, src/redux/features/taskDetailsSlice.ts, src/services/users.ts, src/utils/users.ts
- [LOOM](https://www.loom.com/share/278e41a440d741bda123559bff69078f)
- User can still reassign the parent task to a client out of scope for an iu. And if the subtasks of the parent task is assigned to limited access IU, then there is no way for the IU to access the sub task once the parent is reassigned to a client.
=> OUT-1648 | Filter limited access IU from assignee dropdown in subtasks

src/app/detail/ui/ActivityWrapper.tsx
- [LOOM](https://www.loom.com/share/5564607656e84cbaa97069de276c5cf5)
=> OUT-1682 | Activity logs taking more time than usual to load in the UI.

src/app/api/tasks/public/[id]/route.ts, src/app/api/tasks/public/public.controller.ts, src/app/api/tasks/public/public.dto.ts, src/app/api/tasks/public/public.serializer.ts, src/app/api/tasks/task-notifications.service.ts, src/app/api/tasks/tasks.service.ts
https://github.com/user-attachments/assets/90857738-e804-445d-b1a8-3c8c4cc26a28
Latest update-task notification job has been deployed to staging environment on trigger
=> OUT-1674 | Add support for exposing Update Task API

src/app/api/tasks/public/public.controller.ts, src/app/api/tasks/public/public.dto.ts, src/app/api/tasks/public/public.serializer.ts, src/app/api/tasks/tasks.service.ts
- Also tested all available filter combinations for getAllTasksPublic
=> OUT-1687 | Fix nextToken being sent even when page ends when filters are applied

prisma/migrations/20250428092115_add_source_to_tasks/migration.sql, prisma/schema/task.prisma, src/app/api/tasks/public/public.controller.ts, src/app/api/tasks/public/public.serializer.ts, src/app/api/tasks/tasks.service.ts, src/cmd/load-testing/load-testing.service.ts
=> OUT-1687 | Add support for creating/back-filling "source" column in tasks schema

prisma/migrations/20250430060129_add_optional_task_columns_m14_b/migration.sql, prisma/schema/task.prisma, src/cmd/load-testing/load-testing.service.ts
=> OUT-1693 | Create initial migrations for new Tasks columns

src/app/api/tasks/public/public.dto.ts, src/app/api/tasks/public/public.serializer.ts, src/app/api/tasks/tasks.service.ts
=> OUT-1697 | Implement deletedBy column in Tasks

src/app/api/tasks/public/public.dto.ts, src/app/api/tasks/public/public.serializer.ts, src/app/api/tasks/tasks.service.ts
=> OUT-1695 | Implement completedBy and completedByUserType in Tasks

prisma/migrations/20250501103013_add_task_update_backlogs_table/migration.sql, prisma/schema/task.prisma, prisma/schema/taskUpdateBacklog.prisma, src/app/api/tasks/public/public.controller.ts, src/app/api/tasks/tasks.helpers.ts, src/app/api/tasks/tasks.service.ts, src/jobs/webhook-dispatch/index.ts, src/jobs/webhook-dispatch/queue-task-update-backlog-webhook.ts
https://github.com/user-attachments/assets/eaeab00c-515e-4069-9c35-946c4174b8b0
- `task.updated` hasn't been implemented yet by the Copilot team so the only way to check if this works is by looking at the logs for how many events were dispatched
- Job has been deployed to staging environment on trigger
=> OUT-1699 | Implement transactional log + dispatch-once mechanism for task.updated

src/app/api/core/utils/authenticate.ts
=> OUT-1720 | Passing in a bad token throws a 400 bad request

src/app/api/tasks/tasks.service.ts
=> OUT-1724 | Specify invalid assignee type error when creating a task

src/app/api/tasks/tasks.service.ts
=> OUT-1723 | Not getting a webhook for delete task

src/app/api/tasks/public/public.dto.ts
- [LOOM](https://www.loom.com/share/adc0e0f778694bb8b006f428eb3eb9a2)
=> OUT-1727, OUT-1725 | Description should not be required when creating a task

package.json, src/cmd/backfill-completed-tasks/index.ts
- [LOOM](https://www.loom.com/share/e93eeda2721e45e4b2de59e282398159)
=> OUT-1715 | Backfill completedBy and completedByUserType for older tasks

src/app/api/tasks/tasks.service.ts
=> OUT-1732 | Outdated deleted task object received in webhook response

src/app/api/tasks/tasks.service.ts
=> OUT-1733 | task body showing up as undefined + tempalte.body  

src/app/api/tasks/tasks.service.ts
=> OUT-1735 | CreatedBy field is incorrect

src/app/api/tasks/public/public.dto.ts, src/app/api/tasks/public/public.serializer.ts, src/app/api/tasks/tasks.service.ts
- [LOOM](https://www.loom.com/share/84ff656d4a0243bf9227702c58a08e90)
=> OUT-1734 | do not require name when templateId is present when creating a task

src/app/api/tasks/public/public.dto.ts, src/app/api/tasks/public/public.serializer.ts, src/app/api/tasks/tasks.service.ts, src/types/dto/tasks.dto.ts
=> OUT-1736 | createdBy in body is ignored when creating a task

src/app/api/tasks/public/public.serializer.ts, src/app/api/tasks/templates/templates.service.ts, src/utils/signedTemplateUrlReplacer.ts
- [LOOM](https://www.loom.com/share/64c244e71a7442328e11e755f87a81c4)
=> OUT-1738 | Refresh attachments url for templates while fetching templates and applying templates.

src/components/inputs/Selector.tsx
- [LOOM](https://www.loom.com/share/0a50ac2d0fd5450c855bdde84be22dab)
=> OUT-1750 | Assignee selector unstable, changes placement rapidly on certain dimensions.

src/app/tapwrite.css, src/components/cards/CommentCard.tsx, src/components/cards/ReplyCard.tsx
- [LOOM](https://www.loom.com/share/a3141625cc32437abac24e8c506f6ad1)
=> OUT-1741 | Use text cursor when hovering over description and comment input boxes

.gitignore, package.json, src/cmd/backfill-new-user-ids/index.ts
The task failed for 107 faulty workspaces out of total 18,047 workspaces
A subset of them were confirmed to be faulty (uninstalled app, deleted workspace, etc)
- The script is purposefully synchronous due to ratelimit restrictions
=> OUT-1730 | Backfill companyId for all existing tasks assigned to a client

src/app/api/tasks/public/public.controller.ts, src/app/api/tasks/tasks.service.ts
- [LOOM](https://www.loom.com/share/49da995a2b894bc1bfa36931f8990576)
=> OUT-1794 | Add internalUserId/companyId/clientId filter query params to LIST tasks endpoint

src/app/_fetchers/AssigneeFetcher.tsx, src/app/detail/ui/NewTaskCard.tsx, src/app/detail/ui/styledComponent.tsx, src/app/layout.tsx, src/app/ui/NewTaskForm.tsx, src/components/inputs/CopilotSelector.tsx, src/hoc/ClientSideStateUpdate.tsx, src/hooks/useHandleSelectorComponent.tsx, src/redux/features/taskBoardSlice.tsx, src/types/interfaces.ts, src/types/objectMaps.ts, src/utils/addTypeToAssignee.ts, src/utils/getSelectedUserIds.ts
=> OUT-1767 (Selector Changes)

src/components/layouts/FilterBar.tsx, src/hooks/useFilter.tsx
- [LOOM](https://www.loom.com/share/711db181bc82479797329241a201fa44)
=> OUT-1779, OUT-1819 | Fix task board FilterByAssignee selector to use new userId columns

src/app/detail/ui/NewTaskCard.tsx, src/app/ui/NewTaskForm.tsx, src/components/buttons/ManageTemplatesEndOptions.tsx
=> OUT-1815 | There should only be one separator line in the task template dropdown

src/app/api/tasks/tasks.service.ts
- [LOOM](https://www.loom.com/share/d8d4f7c41d3445c1ad39a00bdaa3a8be)
=> OUT-1872 | Tasks are not being filtered from the api for 2 different companies on client portal

src/app/api/tasks/tasks.service.ts
Problem that was noticed : userIds rolling back to null after updating due date/ workflowstate from details page.
=> TRYFIX OUT-1897 | 'Something went wrong' error in production workspace after clicking on a task in the Tasks App as an IU

src/app/ui/NewTaskForm.tsx, src/hooks/useHandleSelectorComponent.tsx
- [LOOM](https://www.loom.com/share/93ee6f5393e84707af227f459d93e8cb)
=> OUT-1895 | Creating a Task while on filter mode not working

src/app/api/tasks/tasks.helpers.ts, src/app/api/tasks/tasks.service.ts, src/utils/CopilotAPI.ts
=> OUT-1915 | No webhook events triggered when client moves task stages

src/app/api/tasks/public/public.controller.ts, src/app/api/tasks/public/public.dto.ts, src/app/api/tasks/public/public.serializer.ts, src/types/dto/tasks.dto.ts
companyId validation:
- Token was from "ClientRojan Raj" with following company & companyId:
=> OUT-1933 | Improve create task api validation

src/app/api/tasks/tasks.service.ts, src/app/detail/ui/ActivityLog.tsx
=> OUT-1935 | Activity logs shows Company users as undefined when task is unassigned from the company Users.

src/app/api/tasks/tasks.service.ts, src/utils/previewMode.ts
Preview Mode : 
Normal Mode from client :
=> OUT-1943 | Error in client details

src/app/_fetchers/AssigneeFetcher.tsx, src/app/api/tasks/tasks.service.ts, src/app/api/users/users.controller.ts, src/app/api/users/users.service.ts, src/app/detail/[task_id]/[user_type]/page.tsx, src/app/detail/ui/NewTaskCard.tsx, src/hoc/ClientSideStateUpdate.tsx, src/redux/features/taskDetailsSlice.ts, src/services/users.ts, src/utils/users.ts
- [LOOM](https://www.loom.com/share/adb64f5fe0dd4b3e9581cfcfe52cffd3)
=> OUT-1938 | Sub tasks whose parent task is accessible seen on board for Limited Access IUs.

src/app/api/tasks/tasks.service.ts
- [LOOM](https://www.loom.com/share/ecfc996b7f244895bbbdbe0c893a75d9)
=> OUT-1964 | Subtasks are not showing for CU

prisma/migrations/20250716135445_prevent_duplicate_client_notifications/migration.sql, prisma/migrations/20250717103934_prevent_duplicate_migrations/migration.sql, prisma/schema/clientNotification.prisma, src/app/api/notification/notification.service.ts, src/app/api/notification/validate-count/validateCount.service.ts, src/app/api/tasks/subtasks.service.ts, src/app/api/tasks/task-notifications.service.ts, src/cmd/queries/remove-duplicate-notifications.sql
Previously these use cases were causing multiple duplicate notifications to be dispatched for a single task operation
https://github.com/user-attachments/assets/9df154dd-f99f-40fb-9ac1-58453b155d39
https://github.com/user-attachments/assets/07b04a07-4368-4afc-a84f-de15af9283ef
=> OUT-2036 | OUT-2037 | Enforce strict no-duplication mechanism for notification dispatch

src/app/api/notification/notification.service.ts, src/app/api/notification/validate-count/validateCount.service.ts, src/app/api/webhook/webhook.service.ts, src/jobs/notifications/send-reply-create-notifications.ts, src/types/webhook.ts, src/utils/bottleneck.ts
https://github.com/user-attachments/assets/51849d2a-1041-47be-a6cf-6349c89ed808
NOTE: The copilot multi-companies notifications are very buggy. Sometimes the notification chip disappears entirely for no reason.
https://github.com/user-attachments/assets/7b03a406-17e5-4407-a79b-3b17b4d7ff50
https://github.com/user-attachments/assets/5eefe46e-a6b4-4617-842e-429989585ef0
The count cannot be verified from the UI since access to the company is revoked, if if this company is reassigned, the notification count start again from 0, due to the calls to `markNotificationAsRead` when companies are unassigned.
No changes
=> OUT-1985 | OUT-2058 | Support `companyIds` in webhook event Notifications

src/types/common.ts, src/utils/CopilotAPI.ts
https://github.com/user-attachments/assets/e7a4f982-1867-493c-9dc7-3b3d3ab4e95e
=> OUT-2061 | Notifications for other companies are removed when tasks app opens in another company

prisma/migrations/20250723060707_add_last_subtask_updated_timestamp/migration.sql, prisma/schema/task.prisma, src/app/api/tasks/tasks.service.ts, src/app/detail/ui/ActivityWrapper.tsx, src/app/detail/ui/Subtasks.tsx, src/cmd/load-testing/load-testing.service.ts, src/hoc/ClientSideStateUpdate.tsx, src/lib/realtime.ts, src/types/dto/tasks.dto.ts
- created a migration adding lastSubtaskUpdated timestamp in task schema.
- formatted the timestamp for lastSubtaskUpdated in realtime response.
- refetched subtasks according to the change in lastSubtaskUpdated.
- updated lastSubtaskUpdated while creating, updating and deleted a sub task.
- made sure we dont compromise on previously applied optimization by adding refetching check on mount and optimistic updates.
- [LOOM](https://www.loom.com/share/3ec47e64132041d8a8c32fbf6a79b67a)
=> OUT-2055 | Realtime subtask count and subtasks list issues.

package.json, src/cmd/backfill-company-id-in-client-notifications/index.ts, src/cmd/post-deploy-m15/index.ts
=> OUT-2004 | Write a postdeploy script for M15

prisma/migrations/20250728055550_add_user_company_id_field_to_activity_logs/migration.sql, prisma/schema/activityLog.prisma, src/app/api/activity-logs/const.ts, src/app/api/activity-logs/services/activity-log.service.ts, src/app/api/activity-logs/services/activity-logger.service.ts, src/app/api/tasks/tasks.logger.ts, src/lib/patch-jsdom-xhr.cjs
https://github.com/user-attachments/assets/9be92b7b-1fee-41c7-bcda-15d956242805
=> OUT-2053 | Client users are able to see activity logs of users out of their scope

src/app/detail/[task_id]/[user_type]/page.tsx, src/app/detail/ui/Sidebar.tsx, src/utils/assignee.ts
[Loom](https://www.loom.com/share/a9ca1da577b746e69daca4bfa434c24a?sid=0d17129e-8006-465d-a036-aa12f1352d87)
=> OUT-1987: Cache & Revalidate assignee data in browser cache

src/components/inputs/CopilotSelector.tsx
https://github.com/user-attachments/assets/a258522b-ddb9-4492-b03c-782f61202a95
=> OUT-2233 | Removing/switching assignee requires too many clicks

src/app/detail/ui/TaskCardList.tsx, src/app/globals.css, src/components/atoms/CopilotTooltip.tsx, src/components/atoms/TaskMetaItems.tsx, src/components/atoms/TaskTitle.tsx, src/components/cards/TaskCard.tsx, src/components/inputs/CopilotSelector.tsx, src/components/inputs/DatePickerComponent.tsx, src/components/inputs/Selector-WorkflowState.tsx
-[LOOM](https://www.loom.com/share/618d323f2c954256ad26d8dcdf4052d6)
=> OUT-2204 | OUT-2205 | OUT-2206 | OUT-2208 | OUT-2212 | OUT-2216 | OUT-2217 Tooltips should disappear once the cursor leaves hover area

src/app/detail/ui/Sidebar.tsx, src/app/detail/ui/TaskCardList.tsx
=> OUT-2219, OUT-2220 | Update copy on Task Details to match "Set Assignee"

src/app/detail/ui/TaskCardList.tsx, src/components/atoms/CopilotTooltip.tsx, src/components/atoms/TaskTitle.tsx, src/components/cards/TaskCard.tsx, src/components/cards/TaskColumn.tsx, src/components/layouts/DueDateLayout.tsx, src/theme/theme.ts, src/types/theme.d.ts
=> OUT-2213, OUT-2214, OUT-2215 | Increase width of cards from 304px to 336px

src/app/api/notification/notification.service.ts, src/jobs/notifications/send-comment-create-notifications.ts
- a check for preventing duplicate notifications on clientNotificationsTable which is not at all associated with commentId was preventing sending the notifications.
=> OUT-2298 | Comment notifications on email not working

src/lib/realtime.ts
=> OUT-2314 | Adding viewer to a client to a parent task where subtasks are accessible to the client is not reflecting in realtime

src/app/api/tasks/tasks.service.ts, src/app/detail/[task_id]/[user_type]/page.tsx, src/app/detail/ui/Sidebar.tsx, src/components/buttons/SelectorButton.tsx, src/types/interfaces.ts, src/utils/selector.ts
[Loom](https://www.loom.com/share/cad71f05e2de40f8a7b48305c816c709?sid=80013a08-cf75-4cee-986d-88176e9aaf4f)
=> OUT-2318 | OUT-2323: revoke permission to change task status by viewer 

src/utils/CopilotAPI.ts
=> HOTFIX: validate notification count errors 

src/components/buttonsGroup/FilterButtonsGroup.tsx, src/components/layouts/FilterBar.tsx, src/hooks/useFilter.tsx, src/types/interfaces.ts, src/types/objectMaps.ts
[Loom](https://www.loom.com/share/51e944e40a844f6caea1f78640ee317a?sid=d0eb7071-022f-4437-b87d-49a97ad34a91)
=> OUT-2331: Filter by type changes in CU view

src/app/_cache/AssigneeCacheGetter.tsx, src/app/detail/[task_id]/[user_type]/page.tsx
- [LOOM](https://www.loom.com/share/2d00b9a40db54c97a63f89bb892e6a87)
=> OUT-2377 | Task details are missing when opening a task from email notification & notification center

src/app/api/core/utils/withRetry.ts, src/utils/CopilotAPI.ts
=> OUT-2393 | Robust retry mechanism to handle sporadic Copilot API errors

src/components/inputs/CopilotSelector.tsx
- [LOOM](https://www.loom.com/share/e14febcd6bbb4f11a7ceb5159ba6d6db)
=> OUT-2412 | Blurring the Assignee selector attempts to remove Viewer

src/components/layouts/FilterBar.tsx
=> OUT-2453 | Fix FilterBar borders in CRM preview

src/app/api/notification/notification.service.ts, src/app/api/notification/validate-count/validateCount.service.ts
=> OUT-2449 | CU can see the in-product notification for a completed company task

src/app/client/page.tsx, src/app/ui/TaskBoard.tsx
[Loom](https://www.loom.com/share/e12d45e68477418fa5dce32d56599dbe?sid=c829cdfe-8012-42a6-86b6-4a984e04b2d4)
=> OUT-2427: No tasks state in client experience
